### ISSUE TITLE
XFCE: не является браузером по умолчанию

### ISSUE THREAD

**Issue by snejok** [deemru/chromium-gost#1]
В XFCE при каждом запуске выходит "Chromium не является браузером по умолчанию"
Нажатие "Сделать браузером по умолчанию" не помогает.

Судя по strace он пытается выполнить это:
xdg-settings set default-web-browser chromium-browser.desktop
xdg-settings check default-web-browser chromium-browser.desktop

и прописывает в /home/user/.config/xfce4/helpers.rc
WebBrowser=google-chrome

Сделал вручную:
xdg-settings set default-web-browser chromium-gost.desktop

не помогло, думаю потому-что он при старте проверяет так:
xdg-settings check default-web-browser chromium-browser.desktop
и обламывается

Видимо нужно это место допатчить

**Comment by deemru** [comment]
> Видимо нужно это место допатчить

Либо помогайте с патчем, либо ждите -- эта проблема будет с низким приоритетом, так как не касается типичных условий использования и не является проблемой функционирования.

**Comment by linuxbuh** [comment]
Господа может решим это проблему. Готов помочь.

**Comment by deemru** [comment]
> Господа может решим это проблему. Готов помочь.

Конечно -- присылайте патч.

Мне это окружение не знакомо, судя по сообщениям здесь, проблема единичная, поэтому вряд ли будет решено без помощи.

**Comment by linuxbuh** [comment]
Проблема не единичная в XFCE. Не могу понять как включить отладку для выявления

**Comment by linuxbuh** [comment]
Вот что говорит strace до бесконечности когда браузер запущен
d=31, events=POLLIN}], 4, 0) = 0 (Timeout)
recvmsg(30, {msg_namelen=0}, 0)         = -1 EAGAIN (Ресурс временно недоступен)
recvmsg(30, {msg_namelen=0}, 0)         = -1 EAGAIN (Ресурс временно недоступен)
recvmsg(31, {msg_namelen=0}, 0)         = -1 EAGAIN (Ресурс временно недоступен)
recvmsg(31, {msg_namelen=0}, 0)         = -1 EAGAIN (Ресурс временно недоступен)
poll([{fd=11, events=POLLIN}, {fd=12, events=POLLIN}, {fd=30, events=POLLIN}, {fd=31, events=POLLIN}], 4, 5) = 1 ([{fd=12, revents=POLLIN}])
recvmsg(30, {msg_namelen=0}, 0)         = -1 EAGAIN (Ресурс временно недоступен)
read(12, "!", 2)                        = 1
recvmsg(30, {msg_namelen=0}, 0)         = -1 EAGAIN (Ресурс временно недоступен)
recvmsg(31, {msg_namelen=0}, 0)         = -1 EAGAIN (Ресурс временно недоступен)
recvmsg(31, {msg_namelen=0}, 0)         = -1 EAGAIN (Ресурс временно недоступен)
poll([{fd=11, events=POLLIN}, {fd=12, events=POLLIN}, {fd=30, events=POLLIN}, {fd=31, events=POLLIN}], 4, 0) = 0 (Timeout)
recvmsg(30, {msg_namelen=0}, 0)         = -1 EAGAIN (Ресурс временно недоступен)
recvmsg(30, {msg_namelen=0}, 0)         = -1 EAGAIN (Ресурс временно недоступен)
recvmsg(31, {msg_namelen=0}, 0)         = -1 EAGAIN (Ресурс временно недоступен)
recvmsg(31, {msg_namelen=0}, 0)         = -1 EAGAIN (Ресурс временно недоступен)
poll([{fd=11, events=POLLIN}, {fd=12, events=POLLIN}, {fd=30, events=POLLIN}, {fd=31, events=POLLIN}], 4, 2^Cstrace: Process 24911 detached
 <detached ...>

**Comment by linuxbuh** [comment]
Если запустить прогу еще раз при запущенной. то этих ошибок нет + она запускается без сообщения что браузер не по умолчанию

**Comment by linuxbuh** [comment]
Может в XFCE не в ту папку пишет о браузере по умолчанию

**Comment by linuxbuh** [comment]
Посмотрел на TDE - та-же ошибка

**Comment by linuxbuh** [comment]
Дистрибутив https://www.calculate-linux.org/ тоес-ть gentoo

**Comment by linuxbuh** [comment]
На каком дистре вы тестируете

**Comment by snejok** [comment]
Исправление тут #34 

Правда /usr/bin/exo-preferred-applications не будет видеть Chromium GOST в списке браузеров, для этого нужны другие телодвижения https://bugzilla.altlinux.org/show_bug.cgi?id=40502#c1

**Comment by snejok** [comment]
Fixed by #34
