### ISSUE TITLE
Используется программный рендеринг

### ISSUE THREAD

**Issue by mikhailnov** [deemru/chromium-gost#11]
В chromium-gost в `chrome://gpu` почти все желтое, используется программная отрисовка/растеризация:
![DeepinScreenshot_Desktop_20200310233056](https://user-images.githubusercontent.com/15802528/76357135-2fcc9600-6328-11ea-8bea-2f5c99af16a3.png)

При этом в google-chrome-stable там же нет такой проблемы:
![DeepinScreenshot_Desktop_20200310233307](https://user-images.githubusercontent.com/15802528/76357173-407d0c00-6328-11ea-8e12-90223b76fe74.png)

Запуск chromium-gost с `--no-sanbox` не изменяет ситуацию.

Самосборный хромиум с вашими патчами имеет такую же проблему. Завтра скажу, имеет ли такие проблемы ровно тот же самосборный хромиум, но без патчей. Пока что проблема точно есть в ваших сборках.

**Comment by mikhailnov** [comment]
У самосборного Хромиума, но без патчей, такая же проблема, возможно, проблема не имеет отношения к патчам (но в бинарных сборках здесь на гитхабе она есть в любом случае).

**Comment by deemru** [comment]
С большой вероятностью, достаточно установить дополнительный параметр в `gn gen --args`, их там сотни: [List of all gn arguments for Chromium build](https://gitlab.com/noencoding/OS-X-Chromium-with-proprietary-codecs/-/wikis/List-of-all-gn-arguments-for-Chromium-build)

Если будет необходимость, можно покопать в этом направлении. Или, если вы знаете, что можно без ущерба функциональности включить из данного списка, чтобы заработал аппаратный рендеринг, дайте знать.

А пока всё работает без видимых тормозов и, главное, пользователи не жалуются.

**Comment by deemru** [comment]
@mikhailnov вроде полечилось в последних версиях?

![image](https://user-images.githubusercontent.com/10706633/82500570-44819300-9afc-11ea-8435-7a78aab1ae33.png)
