### ISSUE TITLE
Chromium GOST 81.0.4044.92 Не работают групповые политики от Chromium

### ISSUE THREAD

**Issue by chapa72** [deemru/chromium-gost#12]
Доброго времени суток. Разворачиваю Chromium GOST 81.0.4044.92 (x86) на 80 машин (все в домене), до этого использовался Google Chrome. Использую шаблоны от Chromium (брал отсюда https://www.chromium.org/administrators/policy-templates). Chromium GOST устанавливался из exe файла с ключами "--system-level --install --silent". Проблема в том, что браузер никак не реагирует на групповые политики. Значения в реестре прописываются, но судя по всему браузер их даже не проверяет (разделы HKCU(HKLM)\Software\Policies\Google\Chrome). Возможно ли использовать эти значения из реестра? Каким образом можно централизованно управлять параметрами браузера и можно ли? Спасибо.

**Comment by deemru** [comment]
Chromium GOST собирается как Chromium.

Для Chromium сборок используется другая ветка реестра: `Software\Policies\Chromium`

Подробнее: https://github.com/chromium/chromium/blob/master/docs/enterprise/add_new_policy.md

**Comment by chapa72** [comment]
Все оказалось довольно просто: заменил в admx шаблоне все Software\Policies\Google\Chrome на Software\Policies\Chromium . Затем настроил политику, применил, браузер настройки подхватил. Спасибо за наводку. Возможно будет работать не всё, но настройки расширений, поведения при открытии браузера и домашней страницы - работают.
