### ISSUE TITLE
Нет доверия сертификату Фед. казначейства

### ISSUE THREAD

**Issue by finik77** [deemru/chromium-gost#15]
После обновления ФКашного сертификата

![image](https://user-images.githubusercontent.com/39910427/83128530-00425400-a0f5-11ea-83c9-78d8fffe8030.png)
![image](https://user-images.githubusercontent.com/39910427/83128586-0df7d980-a0f5-11ea-8c82-68db29d099e9.png)
![image](https://user-images.githubusercontent.com/39910427/83128615-18b26e80-a0f5-11ea-97f4-d9de4783e8ed.png)

**Comment by deemru** [comment]
У вас что-то другое:
![image](https://user-images.githubusercontent.com/10706633/83132125-9a9c9a80-a0e9-11ea-8880-113bae011d51.png)

Во вкладке Security должно быть больше информации.

У меня например явно:
![image](https://user-images.githubusercontent.com/10706633/83132279-d2a3dd80-a0e9-11ea-8f3d-a569f59a7f6c.png)

![image](https://user-images.githubusercontent.com/10706633/83132398-0252e580-a0ea-11ea-8b46-041d3e1da567.png)

**Comment by finik77** [comment]
У меня 
![image](https://user-images.githubusercontent.com/39910427/83132964-95e0e200-a0fb-11ea-8db3-1fcd651bd194.png)

**Comment by deemru** [comment]
При открытой вкладке Security обновите страницу:

![image](https://user-images.githubusercontent.com/10706633/83133245-409cd480-a0eb-11ea-9b75-88e2e17ae39a.png)

**Comment by finik77** [comment]
![image](https://user-images.githubusercontent.com/39910427/83133282-130c5700-a0fc-11ea-8cc2-bc6a2e60308c.png)

**Comment by deemru** [comment]
Не получается воспроизвести, можете прислать цепочку?

![image](https://user-images.githubusercontent.com/10706633/83134452-0cc2ae80-a0ed-11ea-858d-bd33e4532aed.png)

**Comment by finik77** [comment]
![image](https://user-images.githubusercontent.com/39910427/83134929-81eaaf80-a0fe-11ea-87cd-2bdcba06e043.png)

**Comment by finik77** [comment]
![image](https://user-images.githubusercontent.com/39910427/83135138-d857ee00-a0fe-11ea-9b8b-afdf1776eae9.png)
![image](https://user-images.githubusercontent.com/39910427/83135169-e443b000-a0fe-11ea-8935-5fe8026f3649.png)
![image](https://user-images.githubusercontent.com/39910427/83135194-ee65ae80-a0fe-11ea-911f-c186b3395865.png)

**Comment by deemru** [comment]
Нужны не скриншоты, сами сертификаты можете прислать?

**Comment by finik77** [comment]
Головной, промежуточный, личный
[cert.zip](https://github.com/deemru/chromium-gost/files/4695229/cert.zip)

**Comment by deemru** [comment]
А какая версия у вашего браузера?

![image](https://user-images.githubusercontent.com/10706633/83137281-93798a80-a0f1-11ea-8de2-d9f0435e219b.png)

По идее, он может ругаться на TLS 1.0, этот протокол в зарубежных практиках считается небезопасным, но мы везде этот момент старались купировать, так как в случае ГОСТа он практически ничем от TLS 1.2 не отличается.

**Comment by finik77** [comment]
Странно, у меня ни у одного клиента нет доверия. после смены Федеральным казначейством
![image](https://user-images.githubusercontent.com/39910427/83137686-06d7c800-a103-11ea-8111-2ca53885018e.png)

**Comment by finik77** [comment]
Закрывайте, обновился, нормально стало. Спасибо.

**Comment by deemru** [comment]
По правилам хорошего тона: кто открыл -- тот закрывает.
