### ISSUE TITLE
не работает ppu.admtyumen.ru, www.cryptopro.ru и т.д.: ERR_FAILED (Windows)

### ISSUE THREAD

**Issue by mildok** [deemru/chromium-gost#17]
Добрый день

Пытаюсь заставить это всё работать, но не получается по совершенно непонятным причинам. Код ошибки в браузере, которую получаю при попытке попасть на любой из сайтов, который работает только по ГОСТ — ERR_FAILED. Обычный браузер говорит ERR_SSL_VERSION_OR_CIPHER_MISMATCH, что наводит на мысли, что ГОСТ таки включается, но дальше что-то идёт не так.

КриптоПРО+плагин не совсем работатют - проверку на сайте:
https://www.cryptopro.ru/sites/default/files/products/cades/demopage/cades_bes_sample.html
пройти не могу пишет такую же ошибку...

Однако ж если зайти на страницу проверки с помощью Sputnik browser'а ив настройках ВЫключить поддержку ГОСТ, то пишет такое:
Плагин загружен. 
Версия плагина: 2.0.14071 Версия криптопровайдера: 5.0.11455 
Криптопровайдер: Crypto-Pro GOST R 34.10-2012 Cryptographic Service Provider

Корневые сертификаты федерального казначейства плюс сертификаты ЦИТТО(https://citto.ru/subsections/2) установлены соответственно корневой сертификат и промежуточные

ChromiumGost, YandexBrowser SputnikBrowser с поддержкой отечественной криптографии, Internet Explorer ошибка везде одна и таже.

Пробовал Крипто Про 4.0.9974 и 9963. А также 5.0.11455. Без изменений.

Антивирусник удалён, брандмауэр остановлен.

Windows 8.1 Build 9600
Chromium GOST Версия 84.0.4147.89 (Официальная сборка), (64 бит)

Помогите, пожалуйста, крыша уже едет...

**Comment by x09** [comment]
> Добрый день
> 
> Пытаюсь заставить это всё работать, но не получается по совершенно непонятным причинам. Код ошибки в браузере, которую получаю при попытке попасть на любой из сайтов, который работает только по ГОСТ — ERR_FAILED. Обычный браузер говорит ERR_SSL_VERSION_OR_CIPHER_MISMATCH, что наводит на мысли, что ГОСТ таки включается, но дальше что-то идёт не так.
> 
> КриптоПРО+плагин не совсем работатют - проверку на сайте:
> https://www.cryptopro.ru/sites/default/files/products/cades/demopage/cades_bes_sample.html
> пройти не могу пишет такую же ошибку...
> 
> Однако ж если зайти на страницу проверки с помощью Sputnik browser'а ив настройках ВЫключить поддержку ГОСТ, то пишет такое:
> Плагин загружен.
> Версия плагина: 2.0.14071 Версия криптопровайдера: 5.0.11455
> Криптопровайдер: Crypto-Pro GOST R 34.10-2012 Cryptographic Service Provider
> 
> Корневые сертификаты федерального казначейства плюс сертификаты ЦИТТО(https://citto.ru/subsections/2) установлены соответственно корневой сертификат и промежуточные
> 
> ChromiumGost, YandexBrowser SputnikBrowser с поддержкой отечественной криптографии, Internet Explorer ошибка везде одна и таже.
> 
> Пробовал Крипто Про 4.0.9974 и 9963. А также 5.0.11455. Без изменений.
> 
> Антивирусник удалён, брандмауэр остановлен.
> 
> Windows 8.1 Build 9600
> Chromium GOST Версия 84.0.4147.89 (Официальная сборка), (64 бит)
> 
> Помогите, пожалуйста, крыша уже едет...

А вам не говорили, что вы должны сидеть на Альте?) Где это все прекрасно работает.

**Comment by mildok** [comment]
Да я на всё что угодно готов Базальт линукс, Росинка, Гослинукс и т.д.

Но вот главный бухгалтер не хотит...

**Comment by mildok** [comment]
Нашёл в чём проблема - На компе были какие-то остатки VipNet CSP, хотя в "Установке\удалении програм его не было".


Вообщем - установил "VipNet CSP" заного. Затем деинсталлировал - проблема сразу же исчезла.
