### ISSUE TITLE
Сайты не открываются (--no-sandbox помогает)

### ISSUE THREAD

**Issue by pikachurus** [deemru/chromium-gost#18]
Windows 10 Pro/Windows 7 Pro (с актуальными обновлениями, члены домена)

Ни один сайт не открывается, т.е. если в адресной строке вбить любой урл и нажать ентер - на экране ничего не меняется:
![image](https://user-images.githubusercontent.com/16227309/93001080-3fc26e00-f535-11ea-867f-e6b0d5497f39.png)

Браузер устанавливается без ошибок. В логах Windows тишина. Антивирус (Dr.Web ESS 12) тоже молчит.

Подобное поведение замечаю уже примерно с весны.

С другими браузерами (в том числе на Chromium) таких проблем нет.

В какую сторону можно покопать?

**Comment by deemru** [comment]
> С другими браузерами (в том числе на Chromium) таких проблем нет.

Честной проверкой может быть установка именно Chromium (без ГОСТ) той же версии и битности, например отсюда: https://chromium.woolyss.com/

> В какую сторону можно покопать?

Можно проверить работоспособность:
- без песочницы (--no-sandbox)
- 32-битной версии
- без потенциально конфликтных приложений (Dr.Web)

**Comment by pikachurus** [comment]
Dr.Web я удалял целиком - не помогло.
--no-sandbox - вот это помогло. В браузере сразу появились установленные расширения в системе.
32-битная версия (установленная поверх 64-битной) тоже помогло.
Если снова поверх 32-битной поставить 64-битную - проблема снова тут.
64-битный Ungoogle Chromium работает нормально.

**Comment by deemru** [comment]
Ungoogle Chromium это не Chromium, а очень сильно урезанный Chromium.

В целом, сейчас понятно, что какой-то конфликт в вашем конкретном окружении.

**Comment by deemru** [comment]
@pikachurus удалось разобраться, с каким приложением конфликт?

**Comment by pikachurus** [comment]
В организации зоопарк рабочих станций, включает в себя Windows 7, 8.1, 10. 
Антивирус Dr.Web точно не при чем, т.к. был удален перед началом перебора вариантов.
Единственное, что объединяет эти станции - они члены домена.
Но с другими приложениями (в том числе и браузерами) подобных странностей незамечено, посему непонятно с какой стороны можно зайти в данном случае.

Пока продолжаю перебирать варианты.

**Comment by pikachurus** [comment]
Последний 64-битный релиз 87.0.4280.88 работает нормально, исходной проблемы больше не вижу.
И чистая установка, и поверх 32-битной:
![image](https://user-images.githubusercontent.com/16227309/103487655-08473c80-4e18-11eb-9e5d-490b2f505e4d.png)
