### ISSUE TITLE
Сборка в Linux

### ISSUE THREAD

**Issue by alex-eri** [deemru/chromium-gost#2]
Вот такая ошибка получилась

```
ninja: error: '../../net/msspi.cpp', needed by 'obj/net/net/msspi.o', missing and no known rule to make it
```

**Comment by deemru** [comment]
Крайний поддерживаемый tag с корректной сборкой на Linux: [77.0.3865.90](https://github.com/deemru/chromium-gost/releases/tag/77.0.3865.90), master пока только для Windows доделан.

**Comment by Alzimzim** [comment]
А для Линукс когда будет 77.0.3865.102?

**Comment by deemru** [comment]
Если будет, то не менее 77.0.3865.120, на этой неделе возможно.

**Comment by Alzimzim** [comment]
> Если будет, то не менее 77.0.3865.120, на этой неделе возможно.

Спасибо.
Я и имел ввиду 77.0.3865.120. Просто ошибочно поставил не правильно цифру.
