### ISSUE TITLE
Браузер не проходит проверку на сайте nalog.ru

### ISSUE THREAD

**Issue by leonty** [deemru/chromium-gost#20]
Проверка выполняется для входа в ЛК ИП по ссылке https://lkip2.nalog.ru/certificate/requirements
Версия браузера: 85.0.4183.102
OS: MacOS 10.15.6 
CryptoPro CSP: 5.0.11823

![image](https://user-images.githubusercontent.com/1595354/93074433-04d34e00-f68d-11ea-8039-7689e15d5cd2.png)

**Comment by x09** [comment]
так это камень в сторону налоговой.. они только винду или макось ждут..

**Comment by leonty** [comment]
Так я и пробую на макоси...

**Comment by deemru** [comment]
Проблема в коде проверки на nalog.ru, проверяется не функционал, сравниваются строки версии браузера с зашитыми значениями:

![image](https://user-images.githubusercontent.com/10706633/93079303-93979900-f694-11ea-9e96-b0a8e85f512f.png)

**Comment by leonty** [comment]
Спасибо за информацию. Поменял в дебаггере переменную browser и всё заработало. Может быть вы напишите в поддержку nalog.ru чтобы они включили этот браузер в поддерживаемые? Это единственный бразуер, который работает с ЛК ИП под макосью.
