### ISSUE TITLE
Чёрный экран вместо панорам Яндекс.Карт в Linux

### ISSUE THREAD

**Issue by Alzimzim** [deemru/chromium-gost#21]
Здравствуйте.
Конечно, это не имеет прямого отношения к криптографии, но в Вашем браузере есть проблемы с Яндекс.Картами.
Точнее, не с самими картами, а с Панорамами внутри карт. Если открыть Панораму, то вместо просмотра панорамы улиц будет чёрный экран.

**Comment by deemru** [comment]
- Имеется ввиду Linux?
- Остальные браузеры норм?
- Оригинальный Chromium (который без ГОСТ) норм?

**Comment by Alzimzim** [comment]
> * Имеется ввиду Linux?
> * Остальные браузеры норм?
> * Оригинальный Chromium (который без ГОСТ) норм?

1. Да. Линукс.
2. Я бы так не сказал)) Но, у Яндекс.Браузера точно показывает норм.
3. Затрудняюсь ответить, т.к. я никогда не видел оригинальный браузер Хромиум. Если вы про Гугл Хром, то у меня на компе он не установлен.

**Comment by deemru** [comment]
То есть, выходит, что в Линукс панорамы Яндекс.Карт работают только в Яндекс.Браузере?

Это уже не выглядит как проблема chromium-gost.

**Comment by Alzimzim** [comment]
> То есть, выходит, что в Линукс панорамы Яндекс.Карт работают только в Яндекс.Браузере?
> 
> Это уже не выглядит как проблема chromium-gost.

Вот так это выглядит в  chromium-gost http://screenshot.co/#!/2c9c502b3865 (Где чёрное, там должно быть панорамное фото улицы. Я думаю, у вас откроется, как это выглядит, если Вы перейдёте по этой ссылке https://yandex.ru/maps/geo/moskva/53000094/?l=stv%2Csta&ll=37.191739%2C55.988019&panorama%5Bdirection%5D=308.293042%2C0.000000&panorama%5Bfull%5D=true&panorama%5Bpoint%5D=37.184784%2C55.989736&panorama%5Bspan%5D=120.000000%2C58.536375&source=wizgeo&utm_medium=maps-desktop&utm_source=serp&z=14.2

Я написал выше, что к криптографии это не имеет отношение. Но, наверное, пользователи пользуются Вашим браузером не только ради ГОСТ.

**Comment by deemru** [comment]
Проблема понятна, но сложно судить в чей она зоне компетенции, так как ни в Chromium, ни в Google Chrome панорамы также не работают (проверено на Ubuntu 16.04), а в Яндекс.Браузере и в Firefox работают.

Больше похоже на проблему самих панорам, которой Яндексы должны заниматься.

В рамках chromium-gost задача точно решена не будет.

**Comment by Alzimzim** [comment]
Тогда, с Вашего позволения, я закрою данный тикет.
