### ISSUE TITLE
Не открывается личный кабинет ип https://lkipgost2.nalog.ru/lk

### ISSUE THREAD

**Issue by stiff** [deemru/chromium-gost#22]
Скачал https://github.com/deemru/chromium-gost/releases/tag/85.0.4183.121 , проверку на сайте налоговой не проходит, но вроде на это надо забить и идти прямиком в кабинет, но и там то же самое:
<img width="1312" alt="Screenshot 2020-09-29 at 15 36 31" src="https://user-images.githubusercontent.com/9119/94559207-8e784380-0269-11eb-8db3-4eda18e520e3.png">

Mac OS 10.15.5, CryptoPro CSP стоит, в чём ещё может быть проблема?

**Comment by deemru** [comment]
На самом деле, проблемы при работе с https://lkipgost2.nalog.ru/lk в Сhromium-Gost здесь нет.

Если у пользователя нет клиентских сертификатов, которые можно использовать в рамках соответствующего TLS-подключения, то автоматически происходит попытка анонимного входа (без предъявления сертификата и без окна выбора сертификата), которая в зависимости от обработки на стороне сервера, может как показать страницу с ошибкой (её надо специально создавать на сервере для анонимных пользователей), так и просто завершать TLS-рукопожатие с ошибкой (то что наблюдается у вас).

![image](https://user-images.githubusercontent.com/10706633/94563278-29275100-026f-11eb-8a59-73178fd1b9e0.png)

Пример той же страницы при наличие сертификатов:

![image](https://user-images.githubusercontent.com/10706633/94560501-70abde00-026b-11eb-98d4-2f11be1a9987.png)

А вот пример (https://lk.zakupki.gov.ru/sso/login.jsp), где сообщение об ошибке, при попытке входа без сертификатов, на стороне сервера реализовано нормально:

![image](https://user-images.githubusercontent.com/10706633/94563687-b8346900-026f-11eb-8c1a-fc20d6a6100d.png)

**Comment by stiff** [comment]
Да, очень похоже, не заметил что там сообщение отличается от обычного хрома.
