### ISSUE TITLE
Не работает камера и микрофон

### ISSUE THREAD

**Issue by Akapengo** [deemru/Chromium-Gost#23]
День, добрый. На windows не работает камера и микрофон, кто-то сталкивался с такой проблемой? Тестировали на 30 ПК начиная с 7 заканчивая последней 10. 
для примера сайт https://ru.webcamtests.com/ камера активируется, но изображения нет.

**Comment by deemru** [comment]
Всё так, к сожалению, пока не удаётся разобраться какой дополнительный функционал необходимо активировать при сборке, чтобы камера и микрофон были доступны в браузере.

Если кто знает -- подскажите.

**Comment by Chemyakyn** [comment]
Не скромный вопрос: а там вообще звук есть?
У меня под Линуксом и звук не воспроизводится, не то что камера и микрофон.

**Comment by deemru** [comment]
> Не скромный вопрос: а там вообще звук есть?
> У меня под Линуксом и звук не воспроизводится, не то что камера и микрофон.

Со воспроизведением звука проблем не должно быть.

А в обычном Chromium у всё в порядке?

**Comment by x09** [comment]
подтверждаю проблему со звуком. его нет. в консоль ругается

ALSA lib pcm_dmix.c:1029:(snd_pcm_dmix_open) unable to open slave
[517:517:0128/130043.375379:ERROR:alsa_util.cc(204)] PcmOpen: default,Устройство или ресурс занято
ALSA lib pcm_dmix.c:1029:(snd_pcm_dmix_open) unable to open slave
[517:517:0128/130043.388019:ERROR:alsa_util.cc(204)] PcmOpen: plug:default,Устройство или ресурс занято

**Comment by x09** [comment]
Разобрался с аудио.. видимо, где то в коде хрома забито не default устройство, а чтото типа hw:0,0.. что не очень правильно, как я понимаю.
Решение.
aplay -l смотрим наши устройства воспроизведения
у меня это

```
**** List of PLAYBACK Hardware Devices ****
card 0: NVidia_1 [HDA NVidia], device 0: VT1705 Analog [VT1705 Analog]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: NVidia_1 [HDA NVidia], device 2: VT1705 Alt Analog [VT1705 Alt Analog]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: NVidia [HDA NVidia], device 3: HDMI 0 [HDMI 0]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: NVidia [HDA NVidia], device 7: HDMI 0 [HDMI 0]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: NVidia [HDA NVidia], device 8: HDMI 0 [HDMI 0]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: NVidia [HDA NVidia], device 9: HDMI 0 [HDMI 0]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 2: MicroII [Audio Advantage MicroII], device 0: USB Audio [USB Audio]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
```

мне надо гнать звук на card2 с именем MicroII

делаем файл /tmp/sound.usb

```
pcm.usb { type hw; card MicroII; }
ctl.usb { type hw; card MicroII; }

pcm.!default pcm.usb
ctl.!default ctl.usb
```

запускаем хр-гост и говорим где наш файл
ALSA_CONFIG_PATH=/tmp/sound.usb chromium-gost-stable

звук появился.. может и микрофон, но его у меня нет

**Comment by deemru** [comment]
> Разобрался с аудио

@x09 спасибо.

Но вопрос `А в обычном Chromium у всё в порядке?` задаётся не просто так, возможно это не наша проблема, например, у меня на Ubuntu 20.04 звук работает без вот этих дополнительных настроек.

**Comment by Chemyakyn** [comment]
Конечно же, всё в порядке!
К стати, у меня камера в chromium-gost работает.
Как предложил Антон, заработал и звук. Микрофон - не работает.

```
[AltLinux]# arecord -l
**** List of CAPTURE Hardware Devices ****
card 1: PCH [HDA Intel PCH], device 0: ALC887-VD Analog [ALC887-VD Analog]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: PCH [HDA Intel PCH], device 2: ALC887-VD Alt Analog [ALC887-VD Alt Analog]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 2: U0x46d0x81b [USB Device 0x46d:0x81b], device 0: USB Audio [USB Audio]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
[AltLinux]# aplay -l 
**** List of PLAYBACK Hardware Devices ****
card 0: HDMI [HDA Intel HDMI], device 3: HDMI 0 [HDMI 0]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: HDMI [HDA Intel HDMI], device 7: HDMI 1 [HDMI 1]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: HDMI [HDA Intel HDMI], device 8: HDMI 2 [HDMI 2]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: PCH [HDA Intel PCH], device 0: ALC887-VD Analog [ALC887-VD Analog]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: PCH [HDA Intel PCH], device 1: ALC887-VD Digital [ALC887-VD Digital]
  Subdevices: 1/1
  Subdevice #0: subdevice #0

```

**Comment by mkolesnikov** [comment]
Верися 103.0.5060.134
Ubuntu 22.04 LTS

Все работает и звук, и микрофон и камера, единственное, когда спрашивает разрешения для сайта, то диалога практически не видно, но разрешения можно и в настройках сайта руками раздать.

**Comment by deemru** [comment]
> Верися 103.0.5060.134 Ubuntu 22.04 LTS
> 
> Все работает и звук, и микрофон и камера, единственное, когда спрашивает разрешения для сайта, то диалога практически не видно, но разрешения можно и в настройках сайта руками раздать.

Совсем без танцев с бубном? Может таки закрыть тикет тогда? @Akapengo всё ещё актуальна проблема?
