### ISSUE TITLE
eruz.zakupki.gov.ru ERR_SSL_VERSION_OR_CIPHER_MISMATCH

### ISSUE THREAD

**Issue by burner1024** [deemru/chromium-gost#24]
Добрый день.
Такая ошибка вот.
Пробовал 85.0.4183.83, как в https://www.cryptopro.ru/forum2/default.aspx?g=posts&t=9991&p=27 написано - то же самое.
Долбаный ЕРУЗ вообще ни в одном браузере не работает...
Ubuntu 18.04

**Comment by deemru** [comment]
Не воспроизводится. Попробуйте установить КриптоПро CSP и Chromium Gost ещё раз.

![image](https://user-images.githubusercontent.com/10706633/96270795-c525bc00-0fd4-11eb-8110-add45a7bbf2d.png)

**Comment by burner1024** [comment]
Оказалось, надо убить все процессы ванильного Хромиума, тогда Gost заходит нормально.
