### ISSUE TITLE
86.0.4240.111 macOS error code 9

### ISSUE THREAD

**Issue by outring** [deemru/chromium-gost#25]
В macOS 10.14.6 (18G6020) при попытке открыть любую страницу (в том числе страницу настроек) в версии 86.0.4240.111 показывается стандартная страница ошибки (Aw, snap), из информации об ошибке только `Error code: 9`.
Даунгрейд на предыдущую стабильную версию помогает, она работает как надо.
В `~/Library/Application Support/Chromium/Crashpad/pending` есть дамп, поможет как-то?

**Comment by deemru** [comment]
> В ~/Library/Application Support/Chromium/Crashpad/pending есть дамп, поможет как-то?

Давайте.

**Comment by outring** [comment]
Сорри, что пропал, исправленный релиз работает нормально, так что, полагаю, дамп не понадобится :) Спасибо!
