### ISSUE TITLE
групповые политики

### ISSUE THREAD

**Issue by ikhaltanov** [deemru/Chromium-Gost#26]
как через групповые политики домена установить расширения на все компьютеры? что-то у меня не получилось, мануалы курил

**Comment by ikhaltanov** [comment]
сам спросил, сам ответил:
через групповые политики расширения стоит устанавливать сюда:
\HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Chromium\ExtensionInstallForcelist

**Comment by ikhaltanov** [comment]
корректно не отрабатывает работает только первая строчка принудительной установки(версия 87), у portable  такой проблемы не наблюдается (версия 85)

**Comment by deemru** [comment]
Можно подробно описать проблему, как воспроизвести и имеет ли она отношение к ГОСТ, возможна она имеет отношение к Chromium, тогда вам сюда: https://bugs.chromium.org/p/chromium/issues/list
