### ISSUE TITLE
Не работает сайт https://fzs.roskazna.ru

### ISSUE THREAD

**Issue by sundaleek** [deemru/chromium-gost#28]
version: chromium-gost-88.0.4324.150-macos-amd64.tar.bz2

**Comment by deemru** [comment]
> version: chromium-gost-88.0.4324.150-macos-amd64.tar.bz2

Мало информации для понимания проблемы.

Сайт на MacOS работает нормально:

![image](https://user-images.githubusercontent.com/10706633/108052893-c982e400-705d-11eb-97b6-71a55ffa2775.png)

**Comment by sundaleek** [comment]
@deemru что именно не хватает?

**Comment by deemru** [comment]
> @deemru что именно не хватает?

Так как при штатном использовании проблем не видно, для решения вашей проблемы, вам следует максимально подробно её описать, это включает все шаги по воспроизведению, желательно начиная с шага `берём чистую систему X` и заканчивая `получаем ошибку при открытии сайта Y`.

**Comment by sundaleek** [comment]
1. скачал chromium-gost-88.0.4324.150-macos-amd64.tar.bz2 с этого гитхаба
2. установил(успешно)
3. открыл 
4. перешел на https://fzs.roskazna.ru
5. Тадаам!!
ОС: MacOS 10.15.6 (19G73) Catalina
chromium-gost-88.0.4324.150
Если данной информации недостаточно, уточните конкретнее, что вам нужно

**Comment by deemru** [comment]
То есть, КриптоПро CSP вы не устанавливали вообще?

**Comment by sundaleek** [comment]
> То есть, КриптоПро CSP вы не устанавливали вообще?

Устанавливал. НО сотрудник казначейства сказал, что сайт https://fzs.roskazna.ru/ должен открываться и без него

**Comment by deemru** [comment]
> > То есть, КриптоПро CSP вы не устанавливали вообще?
> 
> Устанавливал. НО сотрудник казначейства сказал, что сайт https://fzs.roskazna.ru/ должен открываться и без него

Этот аргумент легко опровергается, попробуйте открыть в Safari например.

Вот результат открытия в Chromium Gost без КриптоПро CSP:

![image](https://user-images.githubusercontent.com/10706633/109887566-045a5e00-7c93-11eb-8456-e75276727b5a.png)

Если у вас такая же ошибка, то просто не установлен КриптоПро CSP.

**Comment by sundaleek** [comment]
Да. Такая ошибка. Спасибо
