### ISSUE TITLE
Не открывается страница Госуслуг с плагином

### ISSUE THREAD

**Issue by pikachurus** [deemru/chromium-gost#29]
Версии браузера 88 и 89.
Если попытаться зайти на Госуслуги по ЭП (без установленного плагина IFCPlugin), сайт предлагает перейти на страницу с плагином и установить его. В GOST Chromium нужная страница не открывается, выводя 404:
Windows 7 SP1 x64: https://i.imgur.com/zSX6w3a.png
Ubuntu 20.04: https://i.imgur.com/Wit6wsY.png
Данная проблема присутствует и в Windows и в Linux.

**Comment by deemru** [comment]
[404 это ответ веб сервера](https://ru.wikipedia.org/wiki/Ошибка_404), возможно у них неправильная ссылка стоит или какая-то проблема с логикой запроса.

При чём здесь Хромиум Гост?

Проверил, если зайти на https://ds-plugin.gosuslugi.ru -- всё ок, а https://ds-plugin.gosuslugi.ru/plugin/upload/index.spr во всех браузерах выдаёт `Запрашиваемая страница, к сожалению, не найдена`.

**Comment by pikachurus** [comment]
https://ds-plugin.gosuslugi.ru/plugin/upload/Index.spr
вот ссылка, которая нормально открывается в Google Chrome/Mozilla Firefox

Если переходить на страницу с плагином с: https://www.gosuslugi.ru/help/faq/rabota_s_ep/3842

то Google Chrome (и остальные браузеры) нормально отрабатывают ссылку, а GOST Chromium дает 404.

**Comment by deemru** [comment]
1) не воспроизводится
2) даже если бы воспроизводилось, это не проблема браузера

**Comment by deemru** [comment]
Похоже проблема в том, что при работе по ГОСТ сайт ds-plugin.gosuslugi.ru был ошибочно прописан как псевдоним gosuslugi.ru, а в случае работы не по ГОСТ, является отдельной сущностью со своей отдельной конфигурацией.

Легко проверить, при входе на https://ds-plugin.gosuslugi.ru/ в случае ГОСТ не происходит редиректа, а в случае не ГОСТа идёт редирект на https://ds-plugin.gosuslugi.ru/plugin/upload/, что говорит о включении логики отличной от основного сайта.

Передайте в Госуслуги, что в случае ГОСТа они неправильно настроили поддомен ds-plugin.gosuslugi.ru.

Для ГОСТа вход на https://ds-plugin.gosuslugi.ru/plugin/upload/ равносилен входу https://gosuslugi.ru/plugin/upload/, что является ошибкой в их собственной логике:

![image](https://user-images.githubusercontent.com/10706633/112014897-60026380-8b3c-11eb-9a7a-d23891c80cc1.png)
