### ISSUE TITLE
Не видит плагин Госуслуг на Linux

### ISSUE THREAD

**Issue by alex-eri** [deemru/chromium-gost#3]
ХромиумГост не видит плагин Госуслуг. FIX

```
sudo ln -s /etc/opt/chrome/native-messaging-hosts/ru.rtlabs.ifcplugin.json /etc/chromium/native-messaging-hosts/
```

**Comment by deemru** [comment]
То есть, плагин устанавливаемый из Chromium GOST на самом деле прописывается в папку `chrome`, а не `chromium`?

**Comment by alex-eri** [comment]
Плагин из пакета прописывается в `/etc/opt/chrome/`. Opera его видит например и там. А эта сборка хромиума похоже не смотрит в папку для поиска плагинов.

**Comment by deemru** [comment]
Немного не в теме работы плагинов, а это вообще нормально прописываться в папку отличную от рабочей папки текущего браузера, куда тебя устанавливают?

**Comment by alex-eri** [comment]
Сам плагин 2хкомпонентный. Там есть native-messaging-host плагин в пакете для установки в операционку и расширение браузера. Вот тот файлик на который делаю симлинк указывает браузеру запустить плагин при использовании расширения.

Это нормально. Это наверное больше косяк ростелекома. Правильней положить этот плагин в папку хромиума. Но вот другие хромоподобные браузеры смотрят и там и там.

**Comment by deemru** [comment]
Ясно, спасибо за репорт, посмотрим, что можно с этим сделать.

**Comment by leonty** [comment]
Не видит до сих пор...

**Comment by deemru** [comment]
> Не видит до сих пор...

Речь про Линукс? Есть возможность оперативно проверить?

**Comment by leonty** [comment]
У меня макось, могу под ней оперативно проверить.

**Comment by deemru** [comment]
> У меня макось, могу под ней оперативно проверить. В ней тоже не работает.

До этого обсуждалась проблема на Linux, если у вас MacOS, это надо явно указывать, так как системы всё таки существенно отличаются.

А аналог вот этой https://github.com/deemru/chromium-gost/issues/3#issue-503904887 команды для MacOS решает проблему?

**Comment by leonty** [comment]
В MacOS при стандартной установке браузеров в системный раздел Application, папка NativeMessagingHost находится в следующих местах:
Chrome: /Library/Google/Chrome/NativeMessagingHosts
Chromium: /Library/Application\ Support/Chromium/NativeMessagingHosts

И помогает, соответственно, команда:
sudo ln -s /Library/Google/Chrome/NativeMessagingHosts/ru.rtlabs.ifcplugin.json /Library/Application\ Support/Chromium/NativeMessagingHosts/ru.rtlabs.ifcplugin.json

**Comment by deemru** [comment]
@leonty просьба проверить вот эту сборку (без символической ссылки конечно): https://github.com/deemru/chromium-gost/releases/tag/85.0.4183.114

**Comment by leonty** [comment]
Удалил Chromium и /Library/Application Support/Chromium. Установил заново.
Теперь директория NativeMessagingHosts создаётся не в /Library, а в /Users/мойюзер/Library/
Она пустая, плагин не подгружается.

**Comment by deemru** [comment]
> Удалил Chromium и /Library/Application Support/Chromium. Установил заново.
> Теперь директория NativeMessagingHosts создаётся не в /Library, а в /Users/мойюзер/Library/
> Она пустая, плагин не подгружается.

- Что значит `Установил заново`? (в chromium-gost инсталлятора для MacOS нет)

**Comment by leonty** [comment]
Имею в виду перенёс файл из архива в /Applications

**Comment by deemru** [comment]
> После установки плагина и расширения госуслуг ничего не изменилось.

Ошибка и её отсутствие воспроизводится, собираю дебаг, буду смотреть почему не грузит из нужной директории.

**Comment by deemru** [comment]
@leonty, у меня починилось, почему-то был не определён дефайн OS_MAC, пробуйте:
- https://github.com/deemru/chromium-gost/releases/tag/85.0.4183.114-2

@alex-eri, Linux это не коснулось, поэтому прошлая сборка уже должна была решать проблему:
- https://github.com/deemru/chromium-gost/releases/tag/85.0.4183.114

**Comment by leonty** [comment]
После первого запуска нового билда /Users/мойюзер/Library/Application Support/Chromium/NativeMessagingHosts по-прежнему пустая, но при этом всё работает.

**Comment by alex-eri** [comment]
Версия 85.0.4183.114 видит без симлинка.

**Comment by lgg** [comment]
@alex-eri @deemru Version 81.0.4044.122 (Official Build) stable (64-bit)

Пришлось делать symlink, чтобы увидело плагин.

**Comment by deemru** [comment]
@lgg без симлинка должно работать начиная с 85.0.4183.114
