### ISSUE TITLE
Пакетная установка

### ISSUE THREAD

**Issue by evskorobogatij** [deemru/Chromium-Gost#30]
Добрый день

Почему отсутвует msi пакет?
Каким образом автоматизировать установку/удаление ChromiumGOST?

Какие параметры запуска есть у поставляемого exe файла?

**Comment by x09** [comment]
А зачем вам msi, в стране где дни WIndows уже отсчитывают последние мгновения...

**Comment by deemru** [comment]
Вариант `.exe` это mini-installer в терминах проекта Chromium, у него вот такие аргументы: https://source.chromium.org/chromium/chromium/src/+/refs/tags/89.0.4389.90:chrome/installer/util/util_constants.cc

Наиболее используемые сочетания:
- Установить для всех: `installer.exe --system-level --install`
- Удалить для всех: `installer.exe --system-level --uninstall --force-uninstall`

**Comment by MisterTorture** [comment]
> А зачем вам msi, в стране где дни WIndows уже отсчитывают последние мгновения...

Уж три года прошло, а мгновения всё отсчитываются и отсчитываются... Как аттестовывали компы на винде лицензиаты, так и аттестовывают. И как мучились админы, устанавливая exe-пакеты на десятках машин, так и мучиются... И да - сам инсталлятор ехе, видимо, не для винды....
