### ISSUE TITLE
CFBundleName should be changed

### ISSUE THREAD

**Issue by core-code** [deemru/chromium-gost#31]
CFBundleName in the Info.plist should be changed from "Chromium" to "Chromium-Gost"

**Comment by deemru** [comment]
We are not in depth of mac features, why it "should be"? Are there any cons?

**Comment by core-code** [comment]
well.

CFBundleName is the name of the app. if you leave it at 'Chromium' your app is indistuingishable from upstream original Chromium. you've already re-named it in the file-system so it makes sense to also adjust the bundle name.

other Chromium forks like Chedot, Epic, ipDTL, Iron RocketNav and Superbird have also adjusted their CFBundleName.

**Comment by deemru** [comment]
So technically (for an user) there are no real cons and renaming is needed just to make sense and be distinguishable in some mac internals.

We try to update this value in a next release. Thanks.

**Comment by core-code** [comment]
awesome thanks

**Comment by deemru** [comment]
https://github.com/deemru/chromium-gost/commit/af6e1389ed74d43335cab0737eedcf1381762597#diff-1442bb1852f322463b7846df55f396f109ac43811a75b761e426865fe0c1327aR72

done?

**Comment by core-code** [comment]
you are changing the CFBundleIdentifier instead of the CFBundleName. that fullfills the objective (make it distuingishable) but i cannot guarantee that there are no negative side effects in this case.

**Comment by deemru** [comment]
This is it? https://github.com/deemru/chromium-gost/commit/bfdcc37eb328c704ecb536f8a242892dbeed3dbb#diff-1442bb1852f322463b7846df55f396f109ac43811a75b761e426865fe0c1327aR80

**Comment by core-code** [comment]
looks good thanks. will give a definitive confirmation when the next build is out

**Comment by deemru** [comment]
Next build: https://github.com/deemru/chromium-gost/releases/download/90.0.4430.72/chromium-gost-90.0.4430.72-macos-amd64.tar.bz2

**Comment by core-code** [comment]
thanks, i had a look. i can confirm that the CFBundleName has been changed, which is what the bug report was about ("Chromium" => "Chromium-Gost")

i can also confirm that the build has a changed CFBundleIdentifier ("org.chromium.Chromium" => "ru.cryptopro.chromium-gost")
