### ISSUE TITLE
Не заходит на сайты с гостовским шифрованием

### ISSUE THREAD

**Issue by finik77** [deemru/chromium-gost#32]
После обновления на 90.0.4430.72, при заходе на любой ГОСТовский сайт не выходит окно выбора сертификата сразу - 
![image](https://user-images.githubusercontent.com/39910427/114980165-80a4ab80-9ea5-11eb-999b-644dd22cc810.png)

и так любой сайт

**Comment by egzakharovich** [comment]
Подтверждаю. Обновился до версии 90.0.4430.93 - перестал работать ГОСТ TLS.
КриптоПро версии 4.0.9963.

**Comment by deemru** [comment]
https://www.cryptopro.ru/forum2/default.aspx?g=posts&m=124441#post124441

> Выяснили, что модуль Network в Chromium с 90 версии был помещён в песочницу, то есть теперь к библиотекам уровня Network предъявляются повышенные требования.
> 
> Все версии CSP 5.0 удовлетворяют данным требованиям, CSP 4.0 к сожалению нет.
> 
> Поэтому всем пользователям CSP 4.0 для работы TLS в браузере Chromium-Gost версии 90 и выше рекомендуется просто перейти на 5.0, первая сертифицированная версия 5.0.11455 поддерживает приобретённые лицензии от CSP 4.0 в полном объёме.

И как обычно помогает `--no-sandbox`.

**Comment by deemru** [comment]
![image](https://user-images.githubusercontent.com/10706633/134502501-b0680293-d538-4329-94f6-e5eabfb61df5.png)
