### ISSUE TITLE
Вываливается текущий билд на ютубе

### ISSUE THREAD

**Issue by hooddy** [deemru/Chromium-Gost#35]
Обновил поверх предыдущий билд. Теперь при попытке открыть youtube браузер вываливается.
Портативка также себя ведет, стоит только что-то поменять в настройках, неважно что. Сброс настроек на дефолт решает. Расширения отключал, без них тоже самое при изменении настроек.

**Comment by deemru** [comment]
Подтверждаю на Ubuntu 18 воспроизводится, на MacOS и Windows всё ок.

Будем разбираться.

**Comment by hooddy** [comment]
> Подтверждаю на Ubuntu 18 воспроизводится, на MacOS и Windows всё ок.
> 
> Будем разбираться.

А у меня на Винде... Текущий билд 21H2 19044.1110 x64

**Comment by deemru** [comment]
Проблема в коде оригинального проекта.

К сожалению вот такие "стабильные" релизы выпускает @google: https://bugs.chromium.org/p/chromium/issues/detail?id=1231047

Надеюсь исправят оперативно.

**Comment by hooddy** [comment]
Хаха... Гугол такой Гугол...

**Comment by deemru** [comment]
Пофиксили на стороне Ютуба без пересборки, хм, надо внимательно посмотреть на `enable-experimental-web-platform-features` и отключить всю эту прекрасную функциональность.

**Comment by deemru** [comment]
В общем, покопался в текущем коде и не нашёл мест, где бы экспериментальные фичи включались по умолчанию: https://source.chromium.org/chromium/chromium/src/+/main:content/child/runtime_features.cc;l=651;drc=6fdd6d4796fc076fd06f31bce5ea2426e478620c

Предлагаю закрыть до лучших времён.
