### ISSUE TITLE
Не охраняются логин/пароль Google

### ISSUE THREAD

**Issue by hooddy** [deemru/Chromium-Gost#36]
Версия текущая, но и на предыдущей так же. Менеджер паролей не сохраняет данные входа в Гугл, что не удобно. Приходится каждый раз (при запуске браузера) вбивать вручную пароль. Я сперва подумал, что это из-за того, что Гугл запретила сторонним браузерам доступ к учетке, но, например, в SRW Iron (текущая версия на момент репорта) все нормально сохраняется т.е. пароль/логин в Гугл сохраняются. В ГОСТе сохраняется только логин, пароль нет. Я про Windows версию. Можно ли это поправить?

<img width="374" alt="01" src="https://user-images.githubusercontent.com/6899176/127035002-1923e033-0ee6-4f88-9d9e-6ab1b4631ba7.PNG">

**Comment by deemru** [comment]
На форуме (https://www.cryptopro.ru/forum2/default.aspx?g=posts&m=125472#post125472) говорят помогает вот это:

> Если вы хотите протестировать синхронизацию от Google («Вход»):
> 
> 1. Перейдите в https://groups.google.co...wser-signin-testaccounts учетные записи, используя свою учетную запись Google:
> 2. Присоединяйтесь к группе
> 3. Вы можете использовать синхронизацию.
> 
> PS: После присоединения к группе необычных сообщений не будет. Вы по-прежнему будете читать «У вас нет разрешения на доступ к этому контенту». Не волнуйтесь, попробуйте синхронизировать, все заработает!

Кто знает, что необходимо сделать в браузере, чтобы это работало из коробки, дайте знать.

**Comment by hooddy** [comment]
@deemru ссылка на группу ГУгл обрезалась, поправьте, плз. и я все же не про синхронизацию. в том же Iron синхронизация уже не работает (и че6рт бы с ней, все равно любые костыли рано или поздно выбьют, если это и сработает). Я про сохранение пароля от Гугла в менеджере паролей. Это не совсем тоже самое. в других браузерах то работает (я правда проверил только Iron ну и текущий Edge, но им пользоваться из-за кучи секьюрных фич и постоянных блокировок - то сайтов, то загрузки очередного файла, заведомо не вируса/кейгена/крека, а просто какого-либо бинарника - и посика обхода этого безобразия просто боль).

**Comment by arturolegovich** [comment]
Тема по прежнему актуальна, надоело при каждом включении компьютера вбивать пароль для входа в эл. почту gmail.com. А то, что выше предлагается называется Костыль. Как обычному пользователю объяснить, что надо куда то там зайти и какие-то действия проделать. В общем, надо какой-то фикс. Текущая версия 96, а задачка та же самая.

**Comment by deemru** [comment]
Если у кого-то есть решение лучше, готовы взять на вооружение.

Пока ситуация такая (https://www.chromium.org/developers/how-tos/api-keys):
![image](https://user-images.githubusercontent.com/10706633/142668288-9adb097c-cb7e-43b0-82e0-1052b2a57176.png)

**Comment by arturolegovich** [comment]
> Если у кого-то есть решение лучше, готовы взять на вооружение.
> 
> Пока ситуация такая: https://www.chromium.org/developers/how-tos/api-keys

Спасибо, понятно. Пытаться исправить пока бесполезно.

**Comment by arturolegovich** [comment]
То есть раньше работало как то так: https://chromium.woolyss.com/#google-api-keys ? А сейчас это уже не актуально?

**Comment by deemru** [comment]
> То есть раньше работало как то так: https://chromium.woolyss.com/#google-api-keys ? А сейчас это уже не актуально? В любом случае, метод не универсальный и предполагает персональную настройку для каждого аккаунта Google.

Нет, нет, да.

**Comment by hooddy** [comment]
Как-то не работает уже... Раньше работало, у меня на личном профиле я в ту группу присоединился. Но сейчас на работе в профилях сотрудников уже не пускает.

**Comment by deemru** [comment]
Должно было починиться на версии https://github.com/deemru/Chromium-Gost/releases/tag/114.0.5735.110

@hooddy если починилось -- закройте проблему.

**Comment by hooddy** [comment]
Нельзя ли это же фик в версии под win7 добавить?

**Comment by deemru** [comment]
> Нельзя ли это же фикс в версии под win7 добавить? На win 10 завтра гляну. Я уже и забыл ёсли честно за столько времени.

Можно, но в следующей версии.

**Comment by hooddy** [comment]
Тут какой-то странный прикол с учеткой, которой не повезло войти в группу тестирования синхронизации.
Логин и пароль тупо не сохраняются. Т.е. при закрытии браузера и попытке входа в гугол надо опять вводить данные.
с учеткой которая в группе тестирования все вроде норм. Это про версию для Win7.

**Comment by deemru** [comment]
> Логин и пароль тупо не сохраняются. Т.е. при закрытии браузера и попытке входа в гугол надо опять вводить данные.

Об этом и речь. Именно это вылечено в [114.0.5735.110](https://github.com/deemru/Chromium-Gost/releases/tag/114.0.5735.110).

**Comment by hooddy** [comment]
> > Логин и пароль тупо не сохраняются. Т.е. при закрытии браузера и попытке входа в гугол надо опять вводить данные.
> 
> Об этом и речь. Именно это вылечено в [114.0.5735.110](https://github.com/deemru/Chromium-Gost/releases/tag/114.0.5735.110).

Тогда подожду билда под семерку. Пока не закрываем.

**Comment by deemru** [comment]
> Тогда подожду билда под семерку. Пока не закрываем.

https://github.com/deemru/Chromium-Gost/releases/tag/109.0.5414.149

**Comment by hooddy** [comment]
Решено.
