### ISSUE TITLE
Добавление информации о версиях КриптоПро

### ISSUE THREAD

**Issue by Phenixoid** [deemru/Chromium-Gost#37]
Доброго времени суток и спасибо разработчику!

Думаю, было бы неплохо в описание добавить информацию о работоспособности последних версий ХромиумаГост с версиями КриптоПро. То, что на форуме описывалось (версия >90, 5я Крипта, флаг --no-sandbox). Думаю, лишним не будет, ведь "из коробки" браузер не работает в госорганизациях, т.к. то же самое казначейство не выдавало госам 5ю Крипту.

Понимаю, что эта информация есть на форуме, но читать кучу форумов в надежде найти ответ - такое себе..

Спасибо!

**Comment by deemru** [comment]
Доброго, просто в readme или в каждый релиз вносить информацию?

**Comment by x09** [comment]
c 4ой криптой полет нормальный.. но конечно активно переходим на 5ую

**Comment by Phenixoid** [comment]
> Доброго, просто в readme или в каждый релиз вносить информацию?

Так как основной путь (как мне кажется) состоит из переходов Поисковик("ХромиумГОСТ") -> Сайт КриптоПро -> github, то неплохо было бы упомянуть на сайте Крипты (если есть у Вас возможность повлиять на умы создателей Крипты) и в файл readme.md, дабы пользователь прочел предупреждение.

**Comment by Phenixoid** [comment]
> c 4ой криптой полет нормальный.. но конечно активно переходим на 5ую

пробовал на нескольких машинах с 4 криптой и ХГ - не робит, к сожалению, с 5 криптой - из коробки.

**Comment by Phenixoid** [comment]
Тем более, и ишью есть на эту тему (в закрытых), и в ветке форума спрашивали неоднократно

**Comment by deemru** [comment]
> лицензии выданы Казначейством на 4ку

Так лицензии же подходят.

https://www.cryptopro.ru/forum2/default.aspx?g=posts&m=124441#post124441:
> Поэтому всем пользователям CSP 4.0 для работы TLS в браузере Chromium-Gost версии 90 и выше рекомендуется просто перейти на 5.0, первая сертифицированная версия 5.0.11455 поддерживает приобретённые лицензии от CSP 4.0 в полном объёме.

**Comment by deemru** [comment]
@Phenixoid https://github.com/deemru/chromium-gost/releases/tag/92.0.4515.159 так?

**Comment by Phenixoid** [comment]
> @Phenixoid https://github.com/deemru/chromium-gost/releases/tag/92.0.4515.159 так?

прошу прощения за долгий ответ. Да, хорошо получилось.
