### ISSUE TITLE
Постоянно запрашивает авторизацию прокси

### ISSUE THREAD

**Issue by AkhmedzhanovIldar** [deemru/Chromium-Gost#38]
В новой версии хромиум госта постоянно запрашивает авторизацию прокси. После ввода учетных данных проблема не пропадает. В версии 89.0.4389.128 проблема отсутствует и данные автоматом подтягиваются из системы. Проблема наблюдается на WIndows 10

**Comment by big-vl** [comment]
используй плагин для ввода данных прокси и проблема исчезнет.
