### ISSUE TITLE
Выходить и сразу заходить под другим сертификатом

### ISSUE THREAD

**Issue by finik77** [deemru/chromium-gost#4]
как можно в chromium-gost выходить и сразу заходить под другим сертификатом? заходит некоторое время под последним сертификатом на zakupki.gov автоматом

**Comment by algv** [comment]
Не решение, но вдруг пригодится: заходить на сайт во вкладке, режим инкогнито (Ctrl+Shift+N). Тогда открыв новую такую вкладку, chromium точно запросит сертификат

**Comment by s1flashg** [comment]
> Не решение, но вдруг пригодится: заходить на сайт в окне, режим инкогнито (Ctrl+Shift+N). Тогда открыв новое такое окно, chromium точно запросит сертификат

у меня и так не помогает ... чтобы сменить пользователя приходится каждый раз пере запускать браузер 



> Текущее поведение пришло для удобства пользования одним пользователем с одним сертификатом, иначе приходилось "неожиданно" снова вводить пин и выбирать сертификат.
> 
> Сейчас Chromium GOST кэширует сессию пользователя на 10 минут, если по сессии есть активность, таймер обновляется снова на 10 минут.
> 
> Так как кэшируется сессия для пользователя, можно завести несколько пользователей (прямо в браузере) и переключаться между ними.
> 
> Или, как уже предложили, включать режим инкогнито (эмуляция анонимного пользователя).

а можно ли отключить это кеширование во все

**Comment by deemru** [comment]
> а можно ли отключить это кеширование во все

Будет неудобно.

> у меня и так не помогает ... чтобы сменить пользователя приходится каждый раз пере запускать браузер

Что именно не помогает? В чём проявляется? Почему необходимо перезапускать браузер?

**Comment by s1flashg** [comment]
> Что именно не помогает? В чём проявляется? Почему необходимо перезапускать браузер?

даже если войти в режиме иконгито - на сайт закупки ... авторизоватся под одним пользователем, после дать команду выйти ... чтобы после войти но уже под другип пользователем ... сразу входит под первым пользователем .. даже не спрашивает под кем входить запоминает вход до полное перезагрузки браузера

**Comment by deemru** [comment]
> > Что именно не помогает? В чём проявляется? Почему необходимо перезапускать браузер?
> 
> даже если войти в режиме иконгито - на сайт закупки ... авторизоватся под одним пользователем, после дать команду выйти ... чтобы после войти но уже под другип пользователем ... сразу входит под первым пользователем .. даже не спрашивает под кем входить запоминает вход до полное перезагрузки браузера
> 
> PS что интересно в IE11 - такой вот проблемы нет ))

К сожалению вы не поняли последовательности действий. Вход в режим инкогнито равносилен переключению на временного анонимного пользователя. Поработали, закрыли все вкладки, снова вошли в режим инкогнито.

Метод рабочий, постарайтесь понять как им пользоваться.

**Comment by s1flashg** [comment]
а теперь ясно ... открываем новое окно икогнито ... а после закрываем и снова открываем , а основное окно при этом можно не закрывать.
