### ISSUE TITLE
Новые расширения

### ISSUE THREAD

**Issue by RockTheStreett** [deemru/Chromium-Gost#42]
Когда добавляются новые расширения, выдаёт в меню 'Ошибка'. 
По логике, это обычное уведомление. И когда видишь слово 'Ошибка', сразу садишься на пятую точку и первая мысль что что-то сломалось.

Скриншот: https://prnt.sc/1xjukh1

**Comment by deemru** [comment]
Решено в пользу такого варианта:

![image](https://user-images.githubusercontent.com/10706633/156451109-3ede7cdd-d9ed-4685-a89d-af0811f6046b.png)
