### ISSUE TITLE
КриптоПро ЭЦП Browser plug-in

### ISSUE THREAD

**Issue by Urvdmih** [deemru/Chromium-Gost#43]
Доброго времени суток.
У меня есть предложение добавить расширение КриптоПро ЭЦП Browser plug-in в сборку по умолчанию.
Кмк без него браузер не имеет особого смысла, по моему опыту их в связке всегда используют (еще как правило ставят плагин гос. услуг, но он уже реже нужен, хотя от него бы тоже не отказался).

**Comment by deemru** [comment]
> У меня есть предложение добавить расширение КриптоПро ЭЦП Browser plug-in в сборку по умолчанию.

Вы добавите?

**Comment by Urvdmih** [comment]
> > У меня есть предложение добавить расширение КриптоПро ЭЦП Browser plug-in в сборку по умолчанию.
> 
> Вы добавите?

Знал бы как...

**Comment by 19TNR82** [comment]
Так надо установить плагин и расширение само добавиться

**Comment by Urvdmih** [comment]
> Так надо установить плагин и расширение само добавиться

Всегда делал наоборот и думал что расширение вручную ставится. Что-то в голову не приходило что это так работает. Если так, прошу прощения. Можно ишью закрыть.

**Comment by big-vl** [comment]
https://chrome.google.com/webstore/detail/cryptopro-extension-for-c/iifchhfnnmpdbibifmljnfjhpififfog?hl=ru

**Comment by deemru** [comment]
Считаем, что решено: https://github.com/deemru/Chromium-Gost/blob/a210e814be7a1e7da1a1e49bf1075ce89863c5a6/extra/external_extensions.json#L2-L4
