### ISSUE TITLE
Повторно не импортируется сертификат

### ISSUE THREAD

**Issue by sterra-ray** [deemru/Chromium-Gost#44]
Использую Crominm-Gost Версия 96.0.4664.45 (Официальная сборка), (64 бит)
Сразу после установки импортирую личный сертификат в хранилище "Личные", секретные ключи хранятся в реестре. Импортируется сертификат без проблем, без проблем аутентифицируется этим сертификатом на сайте.
Удаляю этот сертификат. Удаляется без проблем, но повторный импорт неудачен. Сообщение об успешном импорте выводится, список сертификатов во вкладке "Личные" остается пустым.
Может быть кто-то сталкивался с подобной проблемой? Что я делаю не правильно?

**Comment by deemru** [comment]
Лучше это спросить на форуме: https://www.cryptopro.ru/forum2/default.aspx?g=topics&f=34

Вообще сложно понять "_Повторный импорт неудачен_" + "_Сообщение об успешном импорте выводится_", может просто из контейнера установить сертификат?

![image](https://user-images.githubusercontent.com/10706633/144395841-822c8d1c-556b-48c2-be74-ff320fb976b2.png)

**Comment by sterra-ray** [comment]
Под "повторным импортом" имеется в виду простое повторение действий импорта. То есть в chromium перехожу по ссылке:  chrome://settings/security, нажимаю "Настроить сертификаты", открывается окошко под названием "Сертификаты", в нем нажимаю "Импорт", далее иду по всем шагам "Мастера импорта сертификатов", в конце появляется окошко с надписью "Импорт успешно выполнен", окошко закрываю кнопкой "ОК", но собственно список в окне Мастера остается пустым. Причем, сертификат укладывается в хранилище успешно - в сертификатной оснастке, в соответствующем хранилище "Сертификаты текущего пользователя -> Личные" присутствует. Переустановка Chromium, очистка истории браузера проблему не решают. Установить сертификат из контейнера нельзя. Сертификат - это отдельный файл, контейнер и запрос на этот сертификат к нему был создан на этой же машине. Контейнер лежит в реестре, сертификата в нем нет. КриптоПро контейнер видит и общается без проблем.

**Comment by deemru** [comment]
> То есть в chromium перехожу по ссылке: chrome://settings/security, нажимаю "Настроить сертификаты"

Зачем? Есть CSP и работа с ГОСТ сертификатами в нём. Хотите новых впечатлений, придётся самостоятельно разбираться и решать проблемы.

В сухом остатке, что-то не работает = не работает TLS двусторонний?

**Comment by sterra-ray** [comment]
В сухом остатке не работает двусторонний TLS. Сертификат удалил ошибочно. Хочу вернуть "как было". Файл сертификата есть, контейнер есть, пароль к контейнеру знаю. Не знаю по какой причине Chromium не импортирует однажды импортированный, но случайно удаленный сертификат.
