### ISSUE TITLE
Версия для Apple M1 [ARM]

### ISSUE THREAD

**Issue by ZonD80** [deemru/Chromium-Gost#45]
Subject. Добавьте пожалуйста еще нативочки:)

**Comment by deemru** [comment]
Может быть, когда-нибудь.

**Comment by deemru** [comment]
https://github.com/deemru/Chromium-Gost/releases/tag/112.0.5615.165

**Comment by rem2akhmad** [comment]
Version 116.0.5845.263 (Official Build) (x86_64 translated) Дико тормозит на M1

**Comment by deemru** [comment]
Давно есть версия для arm64, а также universal для обеих платформ.
