### ISSUE TITLE
Проблема с подписью сертификатом на Госуслугах

### ISSUE THREAD

**Issue by hooddy** [deemru/Chromium-Gost#47]
Подавал заявление на Госуслугах, имею личный сертификат на рутокене. Поставил все плагины, весь хлам от драйверов рутокена до криптоарм и криптопро - на шаге подписи заявления Госуслуги не видят крипто и кидают на страницу загрузки плагинов и расширений (все установлено). Немного повозился, плюнул, на скорую руку установил расширение в Идж и все заверте. Собственно не понимаю, в чем проблема, Хромиум текущий, разве что не установленный, а из зипа распакованный, х64. Как проверить корректную работу и выявить причину?

**Comment by hooddy** [comment]
Думаю, в связи с трансформацией мирового пространства, с сертификатами на рунете возникнет определенная сложность. Подскажите, оставляя в стороне все доводы и спекуляции от MITM для российских сертификатов, вы будете их включать в сборку, как яндекс и атом?

**Comment by big-vl** [comment]
> Подавал заявление на Госуслугах, имею личный сертификат на рутокене. Поставил все плагины, весь хлам от драйверов рутокена до криптоарм и криптопро - на шаге подписи заявления Госуслуги не видят крипто и кидают на страницу загрузки плагинов и расширений (все установлено). Немного повозился, плюнул, на скорую руку установил расширение в Идж и все заверте. Собственно не понимаю, в чем проблема, Хромиум текущий, разве что не установленный, а из зипа распакованный, х64. Как проверить корректную работу и выявить причину?

система какая хоть?
