### ISSUE TITLE
Поиск по умолчанию Яндекс или любой друго Российский

### ISSUE THREAD

**Issue by skylevels** [deemru/Chromium-Gost#49]
Рассматриваем Хромиум-гост как замену Мозиллы на нашем Российском предприятии (около 1000ПК), после того как у Фаерфокса выпилили поиск Яндекса. Также Ваш браузер годиться в качестве «постапокалиптического» инструмента в случае  массового отзыва SSL сертификатов у Российских сайтов. Выпустиои уже несколько Гостовских сертификатов на наши сервера через госуслуги. Вопрос только в поисковой системе. Сделайте пожалуйста поиск по умолчанию Яндекс/МейлРу/Рамблер. Спасибо!

**Comment by deemru** [comment]
> Рассматриваем Хромиум-гост как замену Мозиллы на нашем Российском предприятии (около 1000ПК), после того как у Фаерфокса выпилили поиск Яндекса. Также Ваш браузер годиться в качестве «постапокалиптического» инструмента в случае массового отзыва SSL сертификатов у Российских сайтов.

Рассматривайте Яндекс Браузер, он тоже умеет ГОСТ и его поддержкой занимается более одного человека: https://browser.yandex.ru/help/tls/tls.html

> Сделайте пожалуйста поиск по умолчанию Яндекс/МейлРу/Рамблер. Спасибо!

Если пришлёте патч вносящий предлагаемые изменения, можем внедрить.

**Comment by skylevels** [comment]
> Если пришлёте патч вносящий предлагаемые изменения, можем внедрить.

Увы, не силен в патчестроении. Яндек Браузер, кроме анального зонда и рекламы, подтягивает на комп кучу мелкого софта.

Цель была донести пожелания, если подвернется возможность прошу иметь в виду. Спасибо за труды, удачи!
