### ISSUE TITLE
Существует ли 32 битная сборка?

### ISSUE THREAD

**Issue by finik77** [deemru/chromium-gost#5]

**Comment by finik77** [comment]
Да попадаются еще 32 битные Windows7 у бюджетников(не богатых), не много но есть.

**Comment by deemru** [comment]
Пока только так: https://github.com/deemru/chromium-gost/releases/tag/76.0.3809.132

Или золотая сборка (с поддержкой всех вплоть до XP): https://github.com/deemru/chromium-gost/releases/tag/49.0.2623.112

Пока не видно целесообразности в трате ресурсов на постоянную поддержку 32-битной версии.
