### ISSUE TITLE
Цифровая подпись

### ISSUE THREAD

**Issue by torx25** [deemru/Chromium-Gost#50]
Планируется ли подписывать файлы в дистрибутиве chromium-gost цифровой подписью? Очень неудобно разрешать этот софт для пользователя при включенной политике SRP.

**Comment by deemru** [comment]
Этот релиз (https://github.com/deemru/Chromium-Gost/releases/tag/99.0.4844.84) с подписью устраивает?

**Comment by torx25** [comment]
Спасибо. В этом релизе подписан лишь сам установщик (с ним-то как раз проблем нет, ставится или автоматом, или руками полноправного админа), а я говорил о файлах **в** дистрибутиве, с которыми будет работать ограниченный по правам пользователь. 

Хотя бы .ехе подписать (иначе хэш в политиках надо обновлять каждый раз). Файлы .dll можно скопом по маске разрешить, но и им бы по-хорошему тоже сделать подпись. Тогда всё будет идеально решаться добавлением вашего сертификата в доверенные.

**Comment by deemru** [comment]
https://www.cryptopro.ru/forum2/default.aspx?g=posts&m=136617#post136617:

> Проверьте вот эту версию, дайте знать всё ли устраивает в ней с подписями: https://update.cryptopro.ru/temp/chromium-gost/
