### ISSUE TITLE
Проблема с проверкой условий доступа к личному кабинету на Nalog.ru

### ISSUE THREAD

**Issue by 350d** [deemru/Chromium-Gost#53]
Несколько месяцев назад я пользовался Gost браузером с UA от Яндекс Браузера на сайте nalog.ru и спокойно проходил проверку тут https://lkip2.nalog.ru/lk#!/certificate/requirements
Сейчас проверка не проходится и с и без UA от Яндекс Браузера.
Версия Gost - 101.0.4951.54 OSX
Как теперь заставить работать Gost на nalog.ru?
![Скриншот](https://i.imgur.com/3maDY5r.png)

**Comment by 350d** [comment]
Проблема оказалась в расширении по смене UA. C другим расширением все сработало как надо. Добавьте в Gost возможность указать свой UA пока nalog.ru вас не "признал" официально.

**Comment by deemru** [comment]
https://www.cryptopro.ru/forum2/default.aspx?g=posts&m=88773#post88773

**Comment by 350d** [comment]
> https://www.cryptopro.ru/forum2/default.aspx?g=posts&m=88773#post88773

Так получается ошибка `CERT_EMPTY_OGRN_ERROR`

**Comment by deemru** [comment]
Значит https://lkipgost2.nalog.ru/

**Comment by 350d** [comment]
Тогда Crypto CSP уходит в долгий луп с алертом про `Insert carrier rutoken_lt_***** to open container` и заканчивается все это с `ERR_SSL_PROTOCOL_ERROR `

**Comment by hooddy** [comment]
@350d там нужно выстроить корректно цепочку сертификатов, если что-то не то - не зайдете. т.е. следуя вот этому http://lkul.nalog.ru/check_cryptopro.php установите в доверенные два сертификата - ГУЦ и МКС и установите сертификат физ/юрлица. Также должен быть установлен криптопровайдер (в большинстве случае, это КриптоПРО) и плагин https://chrome.google.com/webstore/detail/cryptopro-extension-for-c/iifchhfnnmpdbibifmljnfjhpififfog
при всех удовлетворяющих требованиях заходит как на https://lkip2.nalog.ru/ так и на https://lkul.nalog.ru/

**Comment by 350d** [comment]
> @350d там нужно выстроить корректно цепочку сертификатов, если что-то не то - не зайдете. т.е. следуя вот этому http://lkul.nalog.ru/check_cryptopro.php установите в доверенные два сертификата - ГУЦ и МКС и установите сертификат физ/юрлица. Также должен быть установлен криптопровайдер (в большинстве случае, это КриптоПРО) и плагин https://chrome.google.com/webstore/detail/cryptopro-extension-for-c/iifchhfnnmpdbibifmljnfjhpififfog
> при всех удовлетворяющих требованиях заходит как на https://lkip2.nalog.ru/ так и на https://lkul.nalog.ru/

На маке у меня заходит только с UA от Яндекс Браузера. Сертификаты установлены, плагин есть.

**Comment by hooddy** [comment]
@350d ну тут надо гемороиться и разбираться. Может и от версии КриптоПРО зависит... 
вот конкретно сейчас на перестановленной Вин11 полез - не работает. быстро настроил, зашел. хромиум гост 89.0.4389.128 (как один из последних который старые вресии tls поддерживает без проблем и сообщений, для работы надо), КриптоПРО 5.0.12417 и сертификаты. заешл как под гостом (вот странно, что он не увидел тестовый сетрификат), так и под спутником (он увидел и тестовый сертификат https://www.cryptopro.ru/certsrv/ и сертификат руководителя.
я иногда плюю и просто Спутником захожу, как меньшим из зол (ну он кроме себя ничего более не ставит, в отличие от яндекса). Не знаю, под мак там есть или нет https://www.sputnik-lab.com/downloads
