### ISSUE TITLE
ВТБ Бизнес не поддердривает ХГ

### ISSUE THREAD

**Issue by hooddy** [deemru/Chromium-Gost#55]
ВТБ бизнес переехал с vtb24 на vtb.ru и видимо что-то понаменял внутри.
Зайти на сервис https://db.vtb.ru/login с текущим билдом невозможно, хотя версия и выше требуемой. Наверное, ему не нравится user agent (chromium gost) или что-то в нем. Писать в чат поддержки на ВТБ ну вообще не вариант, я уже устал общаться с первой линией где угодно, там только мантры из методичек и люди, которые ничего не решают (но я конечно же написал и получил ожидаемый ответ "Вам нужно позвонить по номеру горячей линии  8 (800) 707-24-24." это конечно же чем-то поможет, меня вежливо отошлют на поддерживаемый браузер). @deemru Может у вас есть обходной путь напрямую разрабам писануть, чтобы Гост добавили в поддерживаемые? Ставить ради одного сервиса Яндекс со всеми его свистелками и перделками не хочется. Пока решилось одним из расширений для изменения user agent.

**Comment by deemru** [comment]
> Пока решилось одним из расширений для изменения user agent.

К сожалению, пока на стороне сервера проблему не осознают, придётся на стороне пользователя самостоятельно менять user agent.

Подстроиться на уровне браузера под все сайты невозможно.

Кстати, раз вам удалось проблему обойти, будет хорошо это зафиксировать, какой в итоге рабочий user agent?

**Comment by hooddy** [comment]
`Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.9 Safari/537.36`
некогда было особо разбираться, полез в магазин расширений, третье сработало.
https://chrome.google.com/webstore/detail/user-agent-switcher/dbclpoekepcmadpkeaelmhiheolhjflj
тыкнул в нем в хром и десктоп.

**Comment by hooddy** [comment]
> Подстроиться на уровне браузера под все сайты невозможно

ну я не имел подстроиться Вам, я имел в виду что вы в ВТБ пнете кого-нить из разрабов (вдруг у Вас есть кто-то там знакомый из маганеров или девелоперов), чтобы ваш UA признали валидным. странно, что ВТБ про ваш форк не знают.
