### ISSUE TITLE
Не проходит проверку на сайте налоговой.

### ISSUE THREAD

**Issue by zhilyaev** [deemru/Chromium-Gost#56]
<img width="1187" alt="image" src="https://user-images.githubusercontent.com/4854707/181025056-4637f9fe-d87e-43d4-81cf-bec8b19accf0.png">

<img width="419" alt="image" src="https://user-images.githubusercontent.com/4854707/181025098-eb5f450e-1d68-43ef-bdb7-33c57a8bd53d.png">

**Comment by deemru** [comment]
https://github.com/deemru/Chromium-Gost/issues/53
