### ISSUE TITLE
TLS 1.0

### ISSUE THREAD

**Issue by finik77** [deemru/chromium-gost#6]
В Chromium GOST останется поддержка TLS 1.0?
Deprecate TLS 1.0 and 1.1, targeting removal in Chrome 81 (early 2020). During the deprecation period, sites using those protocols will show a warning in DevTools. After the deprecation period, in 2020, they will fail to connect if they have not upgraded to TLS 1.2 by then.

**Comment by deemru** [comment]
ГОСТовые сюиты работают одинаково хорошо вне зависимости от версии TLS (в отличие от зарубежных сюит), поэтому предпосылок к каким-либо ограничениям в случае ГОСТа нет.

И поддержку TLS 1.0 в случае ГОСТа будем сохранять.
