### ISSUE TITLE
Запуск на M1 в режиме Rosetta

### ISSUE THREAD

**Issue by direktorov** [deemru/Chromium-Gost#61]
При установке на macOS Monterey пишет что не поддерживается установка ?

**Comment by deemru** [comment]
Ожидаемая практика: скачать, разархивировать, запустить.

Что значит установка не поддерживается? Как воспроизвести?

**Comment by direktorov** [comment]
![image](https://user-images.githubusercontent.com/45414898/198585509-d87e4079-afd1-439c-ba20-bfa388db1e67.png)

**Comment by direktorov** [comment]
![image](https://user-images.githubusercontent.com/45414898/198585642-b7767b84-c35d-4a82-a595-ecb4ce958a2d.png)

**Comment by deemru** [comment]
Ясно, действительно, этот нюанс был незамчен при релизе, Гуглы запретели Chromium работать в режиме Rosetta: https://chromium-review.googlesource.com/c/chromium/src/+/3842457

Убрали эти 2 строчки, исправление войдёт в следующий релиз.

Текущий релиз дополнен версией с этим же исправлением, позволяющим запускаться на процессорах Apple Silicon:
https://github.com/deemru/Chromium-Gost/releases/download/107.0.5304.68/chromium-gost-107.0.5304.68-macos-amd64.rosetta.zip
