### ISSUE TITLE
Не запускается на Windows 7 x64. При старте отъедает ОЗУ

### ISSUE THREAD

**Issue by krasnorechiv** [deemru/Chromium-Gost#62]
На компьютерах с Windows 7, с установленными Vipnet CSP, - не запускается Chromium GOST начиная с 100-ой версии. Работает 94-ая.
При запуске происходит следующее:
Появляется окно оформление Chrome, а в диспетчере задач Chrome отъедает всю свободную оперативную память и далее не запускается 
![screenshot](https://user-images.githubusercontent.com/82086854/199497156-1da43b51-aebe-4ce0-9824-fb577369176c.jpg)

**Comment by deemru** [comment]
Очевидно проблема c `Vipnet CSP`.

В рамках Chromium-Gost мы это решать не будем.
