### ISSUE TITLE
ROSA 2014.1 требует libdbus-1.so.3 

### ISSUE THREAD

**Issue by SergeyDjam** [deemru/Chromium-Gost#63]
Ошибка при запуске в ROSA Fresh 2014.1

```
./chromium-gost 
./chromium-gost: /lib64/libdbus-1.so.3: no version information available (required by ./chromium-gost)
./chromium-gost: symbol lookup error: ./chromium-gost: undefined symbol: gbm_bo_get_modifier
```
chromium-gost-stable-109.0.5414.119-1.x86_64

**Comment by deemru** [comment]
Мы тут не при чём, так решили разрабочики Chromium, а вникать во все нюансы разработки браузера физически невозможно.

Если это кажется ошибкой, присылайте patch.

**Comment by SergeyDjam** [comment]
Ок. Если получится, пришлю

**Comment by big-vl** [comment]
> Ок. Если получится, пришлю

libdbus-1-dev - она используется?
