### ISSUE TITLE
Не проходит проверку на сайте https://arm-fzs.roskazna.gov.ru/

### ISSUE THREAD

**Issue by lea-id** [deemru/Chromium-Gost#64]
Добрый день.

Стоял chromium-gost-stable-99.0.4844.51-1.x86_64. Проверку проходил успешно.
Перепробовал все версии старше этой. Проверку не проходит. Идентифицируется как Chrome.
Установил chromium-gost-stable-110.0.5481.96-1.x86_64. Результат тот же.
![Screenshot from 2023-03-01 10-04-34](https://user-images.githubusercontent.com/1483919/222024863-f40d120b-c5ac-4d30-a92e-ee1ce9e4584c.png)
![Screenshot from 2023-03-01 10-36-40](https://user-images.githubusercontent.com/1483919/222024886-e0bdd010-ed43-439f-a3d0-f2e38cd1138f.png)

**Comment by big-vl** [comment]
> Добрый день.
> 
> Стоял chromium-gost-stable-99.0.4844.51-1.x86_64. Проверку проходил успешно. Перепробовал все версии старше этой. Проверку не проходит. Идентифицируется как Chrome. Установил chromium-gost-stable-110.0.5481.96-1.x86_64. Результат тот же. ![Screenshot from 2023-03-01 10-04-34](https://user-images.githubusercontent.com/1483919/222024863-f40d120b-c5ac-4d30-a92e-ee1ce9e4584c.png) ![Screenshot from 2023-03-01 10-36-40](https://user-images.githubusercontent.com/1483919/222024886-e0bdd010-ed43-439f-a3d0-f2e38cd1138f.png)

Вижу что linux, сноси Chromium-Gost, устанавливай последний хром, ставь CryptoPro, устанавливай плагины:
https://chrome.google.com/webstore/detail/cryptopro-extension-for-c/iifchhfnnmpdbibifmljnfjhpififfog?hl=ru
https://chrome.google.com/webstore/detail/user-agent-switcher-and-m/bhchdcejhohfmigjafbampogmaanbfkg

![image](https://user-images.githubusercontent.com/60448373/226173328-6dc85a38-e6d5-4fa8-9ef6-bfef0655d6fa.png)
вписывай в User-Agent: 
`Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36 (Chromium GOST)`

жми Apply (all window), рядом кнопка Restart.

**Comment by big-vl** [comment]
переходи на сайт и все должно работать. Это ограничение в linux. Жаль что нет закона о нарушение импорта замещения.

**Comment by egzakharovich** [comment]
Забудьте про этот сайт уже.

Его с 2020-21 года никто не актуализировал (выложили и забыли, называется). А ругаться на браузер он начал ещё с Chrome 100-ой версии, ЕМНИП.

Дело именно в том, что там 3 циферки, а не 2. И это нужно исправить разработчику сайта, а не браузеру, потому Issue по идее закрыть надо.

Я это как "эксперт" по настройке доступа к бюджетам говорю. :)
