### ISSUE TITLE
Релизы выше chromium-gost-109.0.5414.119 на семерке вываливаются с ошибкой

### ISSUE THREAD

**Issue by hooddy** [deemru/Chromium-Gost#65]
Собственно сабж. При запуске вываливаются с ошибок "точка входа не найдена в kernel.dll"
Откатился.

**Comment by deemru** [comment]
Это не наше решение: https://support.google.com/chrome/thread/185534985/sunsetting-support-for-windows-7-8-8-1-and-windows-server-2012-and-2012-r2-in-early-2023

Однако, ветку 109 не бросаем, будут ещё релизы с большой вероятностью.

**Comment by hooddy** [comment]
я понял.
