### ISSUE TITLE
Разные теги

### ISSUE THREAD

**Issue by alealexpro100** [deemru/Chromium-Gost#66]
Возможно ли добавление тегов для версий, собранных для windows 7?
На данный момент теги для обычных версий и версий с поддержкой старых ОС имеют теги одинакового вида, что не очень удобно для автоматизации обновления [как здесь](https://github.com/alealexpro100/ru-school-scoop/blob/master/bucket/chromium-gost.json).

**Comment by deemru** [comment]
"Как здесь" это как? Лучше покажите пример того, что хотите.

По смыслу 109 ветка последняя с поддержкой Windows 7, можно вполне считать подстроку "109.0.5414." Тем о чём вы говорите.

**Comment by alealexpro100** [comment]
Похоже, что ветка 109 - действительно будет последней версией для Winodws 7. API GitHub-а предотвращает использовние более старой версии. Смысла в изменении в тегах, похоже, нет.
