### ISSUE TITLE
Не запускается установка Chromium-Gost

### ISSUE THREAD

**Issue by 12567890** [deemru/Chromium-Gost#67]
Скачал гост  с криптопро . Запускаю от имени администратора. Создается временная папка и пропадает, Сам браузер не запускается. в списках программ не числится. ОС Windows 8.1 x 64

**Comment by deemru** [comment]
Зачем от имени администратора?

При наличии проблем следует указывать подробную пошаговую инструкцию.

Также можно воспользоваться вариантом без установки в систему (архив .zip).

**Comment by deemru** [comment]
Какая версия не работает? Вот эта? -- https://github.com/deemru/Chromium-Gost/releases/tag/109.0.5414.129

Или пропустили новость? -- https://support.google.com/chrome/thread/185534985/sunsetting-support-for-windows-7-8-8-1-and-windows-server-2012-and-2012-r2-in-early-2023

**Comment by SunTehnikNaN** [comment]
Спасибо, новость действительно пропустил. 109 версия на Win 7 запускается корректно

**Comment by s1flashg** [comment]
кажется еще это работает  на 7 и 8.1  - https://github.com/deemru/Chromium-Gost/releases/tag/109.0.5414.173
