### ISSUE TITLE
Не открывает вкс в браузере

### ISSUE THREAD

**Issue by honbregordo** [deemru/Chromium-Gost#72]
Добрый день, столкнулся с такой проблемой: 
Версия Chromium gost 108.0.5359.98
при переходе по ссылке конференции в conf.mosreg не предлагается запустить данную конференцию в окне браузера, а только  через приложение, хотя в других браузерах (google chrome версии 109.0.5414.120  и яндекс браузер версии 23.7.0.2526 (64-bit)) присутствует вариант просмотра через браузер
![141](https://github.com/deemru/Chromium-Gost/assets/140700446/073103e9-0132-4571-b73e-14345b730d6b)
![Screenshot_5](https://github.com/deemru/Chromium-Gost/assets/140700446/f8507d62-dbd9-4076-855b-095e890c5e10)

Подскажите, пожалуйста, есть ли возможность настроить браузер так, чтобы можно было просматривать вкс через окно браузера?

**Comment by deemru** [comment]
Вообще это не проблема браузера, а скорее проблема сайта.

[Говорят](https://cryptopro.ru/forum2/default.aspx?g=posts&m=137371#post137371), что через опцию командной строки можно прикинуться любым браузером, например таким:
```
chrome --user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36"
```

**Comment by honbregordo** [comment]
Большое спасибо, тогда буду использовать какой-нибудь User-Agent Switcher
