### ISSUE TITLE
Синхронизация аккаунта Google

### ISSUE THREAD

**Issue by karabelnikov** [deemru/Chromium-Gost#74]
В последней версии Chromium Gost для Windows 7 (109.0.5414.149) пропала кнопка "Включить синхронизацию". В предпоследней версии она есть. С чем это связано и как решить?

![Снимок экрана 2023-08-30 в 17 16 30](https://github.com/deemru/Chromium-Gost/assets/11692792/9ce99296-8018-477d-a2bb-4c17e4480b41)

**Comment by deemru** [comment]
- https://github.com/deemru/Chromium-Gost/issues/36
- https://github.com/deemru/Chromium-Gost/issues/70
