### ISSUE TITLE
Билд 117 не работает на Win10 1507, в отличие от предыдущего 116

### ISSUE THREAD

**Issue by hooddy** [deemru/Chromium-Gost#75]
![01](https://github.com/deemru/Chromium-Gost/assets/6899176/06b93083-35e5-4b43-bc07-1cf6706f86cd)
Собственно, скриншот. Win101506LTSB 10.0.10240

**Comment by deemru** [comment]
Что тут сказать, в Гугле "хорошие" тестировщики:
- https://support.google.com/chrome/thread/234827907
- https://github.com/brave/brave-browser/issues/33058

Это исправлено, критичности выпуска нет, поэтому в следующей сборке должно работать без ошибок на вашей системе.

**Comment by deemru** [comment]
https://github.com/deemru/Chromium-Gost/releases/tag/117.0.5938.92
