### ISSUE TITLE
Автоматизация Selenium

### ISSUE THREAD

**Issue by IvanSheludiakov** [deemru/Chromium-Gost#76]
Добрый день! Есть ли возможность использовать selenium с браузером Chromium-Gost?

**Comment by deemru** [comment]
С ходу проблем не видно, должно работать.

**Comment by RomanZorkin** [comment]
Вот такой код предлагает chatgpt. В целом понятно, но где взять веб драйвер? 


'''Python
from selenium import webdriver

from selenium.webdriver.chrome.service import Service

from selenium.webdriver.chrome.options import Options

# Укажите путь к исполняемому файлу Chromium-GOST

chromium_gost_path = '/path/to/chromium-gost'

# Создайте объект Options и настройте параметры браузера

chrome_options = Options()

chrome_options.binary_location = chromium_gost_path

# Укажите путь к веб-драйверу Chromium-GOST

webdriver_service = Service('/path/to/chromedriver')

# Создайте экземпляр веб-драйвера с указанными опциями и сервисом

driver = webdriver.Chrome(service=webdriver_service, options=chrome_options)

# Откройте веб-страницу

driver.get('https://www.example.com')

# Выполните необходимые действия с помощью Selenium

# Закройте браузер

driver.quit()
'''

**Comment by deemru** [comment]
> но где взять веб драйвер?

Кроме "chatgpt" есть обычный поиск, который сразу выдаёт правильный ответ: https://chromium.googlesource.com/chromium/src/+/refs/heads/main/chrome/test/chromedriver#chromedriver

**Comment by RomanZorkin** [comment]
В целом получилось, поделюсь:
1. Начну с кода python
```python
# место расположения установленного браузера.
browser_app = '/usr/bin/yandex-browser'

# место расположения скачанного драйвера Chromium-gost
chrome_driver = 'data/yandex/chromedriver'

options = webdriver.ChromeOptions()
options.binary_location = browser_app

driver=webdriver.Chrome(options=options, service=Service(chrome_driver))
driver.get('https://ya.ru/')
```

2. Чтобы узнать расположение установленного у вас браузера (в нашем случае chromium-gost) в Linux введите команду 
```bash
which chromium-gost
```

3. Теперь про Chromium-gost драйвер. Дело в том, что Chromium-gost, создан на основе проекта Chromium. Их драйверы идентичны, поэтому идем https://developer.chrome.com/docs/chromedriver/downloads и ищем там подходящий релиз.
Чтобы узнать текущий релиз открываем свой браузер, идем в настройки ищем "About Chromium-Gost". Там будет примерно так "Версия 129.0.6668.70 (Официальная сборка), stable (64 бит)". Это и есть версия драйвера. 
На странице загрузки подходящей версии может не ОКАЗАТЬСЯ. Обратите внимание, что на этой странице есть ссылка на json файл https://googlechromelabs.github.io/chrome-for-testing/known-good-versions-with-downloads.json (ссылка на момент комментария).В этом файле необходимо найти свою версию. Далее внутри словаря по ключу ['downloads']['chromedriver'] выбрать подходящую ссылку для вашей операционной системы.
