### ISSUE TITLE
Ошибка при старте "Отказано в доступе" в Ubuntu

### ISSUE THREAD

**Issue by sercxjo** [deemru/Chromium-Gost#78]
После обновления ubuntu до версии noble при старте выдаёт ошибку:
```
[50012:50012:1220/164845.344667:FATAL:credentials.cc(127)] Check failed: . : Отказано в доступе (13)
Ловушка трассировки/останова (образ памяти сброшен на диск)

```
Ошибку можно обойти запустив с ключом --no-sandbox

**Comment by deemru** [comment]
Общая проблема Сhromium подобных браузеров:
https://yandex.ru/search/?text=ubuntu+noble+credentials.cc(127)

Кто виноват и кто будет её решать неизвестно, но в рамках Chromium-Gost заниматься ей не будем.

**Comment by sercxjo** [comment]
Спасибо за ссылку, мои поисковые запросы почему-то не давали подходящего результата.
Всё же луче было бы, если бы программа выдавала более вразумительное сообщение.

**Comment by sercxjo** [comment]
Судя по логу это связано с новыми ограничениями в ubuntu к пространствам имён:
`kernel: [285692.508470] audit: type=1400 audit(1703419461.116:707): apparmor="DENIED" operation="userns_create" class="namespace" in
fo="User namespace creation restricted" error=-13 profile="unconfined" pid=441335 comm="chrome" requested="userns_create" denied="userns_create"`

Однако для в ubuntu noble проблема решена для chrome, brave  и нескольких других браузеров конфигурацией apparmor, но он ничего не знает о chromium-gost. Для решения проблемы нужно добавить файл в /etc/apparmor.d/
```
abi <abi/4.0>,
include <tunables/global>

/opt/chromium-gost/chrome flags=(unconfined) {
  userns,
}

```

**Comment by neowisard** [comment]
Уточню инструкцию для таких как я , пошагово )
1. Создать файл /etc/apparmor.d/chrominium-gost с текстом
 `abi <abi/4.0>,
include <tunables/global>

/opt/chromium-gost/chrome flags=(unconfined) {
  userns,
}
`
2. Перезапусть apparmor  sudo systemctl reload apparmor.service
