### ISSUE TITLE
CSS стиль вызываем моргание сайдбара

### ISSUE THREAD

**Issue by unw1ck3d** [deemru/Chromium-Gost#79]
Имеется div элемент с указанным стилями. 
`
position: sticky;
z-index: var(--zIndexMenu);
top: 0;
height: calc(100vh - 55px);
`
В интерфейсе появилась проблема, что при частых действиях внутри самого блока и, как результат, вызова замены элементов через innerHTML, элементы внутри стали отрисовываться частично или вовсе пропадать. Элементы возвращались после какого-либо действия с этим блоком, либо через выделения в инспекторе. 

После того, как был убран стиль height: calc(100vh - 55px); - проблема ушла.
Просьба разобрать причину

**Comment by deemru** [comment]
В этом репозитории принимаются в основном проблемы по TLS функционалу связанному с ГОСТ.

У вас явно проблема не по адресу, вам сюда: https://bugs.chromium.org/p/chromium/issues/list
