### ISSUE TITLE
*.nalog.ru не работает: ERR_FAILED (macOS)

### ISSUE THREAD

**Issue by outring** [deemru/chromium-gost#8]
Добрый день

Пытаюсь заставить это всё работать, но не получается по совершенно непонятным причинам. Код ошибки в браузере, которую получаю при попытке попасть на любой из сайтов, который работает только по ГОСТ — `ERR_FAILED`. Обычный браузер говорит `ERR_SSL_VERSION_OR_CIPHER_MISMATCH`, что наводит на мысли, что ГОСТ таки включается, но дальше что-то идёт не так.

КриптоПРО+плагин работают нормально, [проверку](https://www.cryptopro.ru/sites/default/files/products/cades/demopage/simple.html) прохожу успешно. Пункты для работы на nalog.ru из [инструкции](https://support.cryptopro.ru/index.php?/Knowledgebase/Article/View/232/0/rbot-s-kriptopro-csp-v-macos) тоже выполнены.

Прикладываю следующие логи (v1):
* [gost.cryptopro.ru.log](https://github.com/deemru/chromium-gost/files/3840067/gost.cryptopro.ru.log) — лог соединения с https://gost.cryptopro.ru, который работает [полностью нормально](https://user-images.githubusercontent.com/150131/68745237-5511f780-0607-11ea-995b-8d490010b7c1.png)
* [lkul.nalog.ru.cert.log](https://github.com/deemru/chromium-gost/files/3840069/lkul.nalog.ru.cert.log) — попытка доступа на https://lkul.nalog.ru с использованием сертификата (нормально запрашивается перед соединением), но заканчивается всё ERR_FAILED
* [lkul.nalog.ru.nocert.log](https://github.com/deemru/chromium-gost/files/3840068/lkul.nalog.ru.nocert.log) — попытка доступа на https://lkul.nalog.ru без использования сертификата (когда сертификатов в системе нет), но заканчивается всё ERR_FAILED

Логи почитал и ничего дельного в них не увидел, может вам будет яснее, ну или посоветуете что-нибудь. 
Спасибо

macOS 10.14.6 (18G103)
Chromium GOST Version 78.0.3904.87 (Official Build) (64-bit) (пробовал также 77)
CryptoPro Extension for CAdES Browser Plug-in 1.2.7
CryptoPro CSP 5.0.11455 (пробовал также 4R4)

**Comment by deemru** [comment]
В логах имеется: ```Insert carrier rutoken_lt_37157e95 to open container SCARD\rutoken_lt_37157e95\0B00\F947```

Токен рабочий? В cptools проверки проходит?

**Comment by outring** [comment]
О каких проверках речь? В cptools токен видно, сертификат с него удалось установить и сделать тестовую подпись на https://www.cryptopro.ru/sites/default/files/products/cades/demopage/simple.html
Сертификат, кстати ГОСТ Р 34.10-2001, не знаю, имеет ли это значение. Но разве SSL не должен без сертификата работать?

**Comment by deemru** [comment]
Односторонний TLS может работать без сертификата, но при входе в личный кабинет nalog.ru устанавливается двусторонний TLS, с аутентификацией по сертификату в рамках TLS.

Вот сейчас проверил, выбрал первый попавшийся сертификат, тоже получил ERR_FAILED.

Это означает, что на nalog.ru при неполучении в рамках TLS необходимого ему сертификата, просто разрывает соединение.

**Comment by outring** [comment]
О, круто, теперь понятно, спасибо! Было бы здорово получить какой-нибудь более конкретный код ошибки в таком случае, сильно упростило бы дебаг.
