### ISSUE TITLE
не подключается синхронизация с гугл

### ISSUE THREAD

**Issue by zinovevvv** [deemru/Chromium-Gost#80]
Сделал все по инструкции https://www.chromium.org/developers/how-tos/api-keys/#providing-keys-at-runtime
и сохранил ключи
GOOGLE_API_KEY=""
GOOGLE_DEFAULT_CLIENT_ID=""
GOOGLE_DEFAULT_CLIENT_SECRET=""
кнопочка подключить синхронизацию появилась, но после ввода логина и пароля синхронизация все равно не включается

**Comment by zinovevvv** [comment]
извиняюсь не все по инструкции сделал, нужно было выбрать тип приложение десктоп
<img width="678" alt="image" src="https://github.com/deemru/Chromium-Gost/assets/60914683/c05a2201-b7fe-4320-bec3-d6c7e8740fcb">

**Comment by zinovevvv** [comment]
вообщем если заходить через командную строку то работает, если хоть раз просто открыть Chromium-Gost.app то сразу синхронизация слетает

**Comment by hooddy** [comment]
Простите, вклинюсь. Мне вот больше интересно, почему в thorium синхра с гуглом без шаманства просто есть. Да и под семерку последние билды, а не 109 билд.

**Comment by deemru** [comment]
> вообщем если заходить через командную строку то работает, если хоть раз просто открыть Chromium-Gost.app то сразу синхронизация слетает

Всё логично, закрываем.
