### ISSUE TITLE
Не открывется сайт vaccine.egisz.rosminzdrav.ru

### ISSUE THREAD

**Issue by Rudikoz** [deemru/Chromium-Gost#83]
![image](https://github.com/deemru/Chromium-Gost/assets/160816189/bcd12cb9-dfe7-4deb-a4a1-e65bd678a87f)
Не открываются сайты vaccine.egisz.rosminzdrav.ru и covid.egisz.rosminzdrav.ru, должна пройти переадресация на сайт госуслуг для авторизация, но в консоли выходит ошибка как на скрине. В других браузерах данная проблема не наблюдается

**Comment by deemru** [comment]
Проблема в скриптах на сайте, которые некорректно интерпретируют [User-Agent](https://ru.wikipedia.org/wiki/User_agent) браузеров, немного отличающихся от ожидаемых, делают на основе этой интерпретации неправильные выводы, что приводит к ошибкам в самих скриптах. Как показывает практика, движок браузера ещё ни разу не являлся причиной и работает корректно.

Похожие проблемы:
- https://github.com/deemru/Chromium-Gost/issues/55
- https://github.com/deemru/Chromium-Gost/issues/72

Легко проверить, что ваш случай тоже решается аналогично, например так:
```
chrome --user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36"
```

В Chromium-Gost используется вот такой патч для идентификации себя среди прочих User-Agent: https://github.com/deemru/Chromium-Gost/blob/d6c944f94bdc93a721be824fb593eb654cde526a/patch/chromium.patch#L794-L795

**Comment by Rudikoz** [comment]
Спасибо за помощь, ваше решение работает. Буду долбить разработчика сайта
