### ISSUE TITLE
настройка прокси

### ISSUE THREAD

**Issue by olzvong163** [deemru/Chromium-Gost#90]
Добрый день, при использовании модифицированного файла /etc/chromium/default
export CHROMIUM_FLAGS="-proxy-server=имя_прокси:порт"
Браузер chromium корректно работает с прокси, а вот chromium-gost нет. Как настроить chromium-gost для работы через прокси?
Прокси работает на squid v.3.5.20, используется аутентификация Negotiate (он же Kerberos).

**Comment by deemru** [comment]
> при использовании модифицированного файла /etc/chromium/default
> export CHROMIUM_FLAGS="-proxy-server=имя_прокси:порт"
> Браузер chromium корректно работает с прокси, а вот chromium-gost нет

Это документированный функционал? Не нашёл его в коде, есть ссылки на документацию?

> Как настроить chromium-gost для работы через прокси?

Запускать Chromium-Gost с указанием прокси:
`/opt/chromium-gost/chrome --proxy-server=имя_прокси:порт`
