### ISSUE TITLE
Неудовлетворенные зависимости на Альт СП 9

### ISSUE THREAD

**Issue by evlanoff** [deemru/Chromium-Gost#92]
Добрый день.

Обновил браузер с 126.0.6478.182 до 127.0.6533.88, делаю `# apt-get dist-upgrade` и получаю unmet dependencies. Лог:

```
apt-get dist-upgrade
Чтение списков пакетов... Завершено
Построение дерева зависимостей... Завершено
You might want to run `install --fix-broken' to correct these.
Следующие пакеты имеют неудовлетворенные зависимости:
  chromium-gost-stable: Требует: (libcurl.so()(64bit) or libcurl-gnutls.so.4()(64bit) or libcurl-nss.so.4()(64bit) or libcurl.so.4()(64bit)) но пакет не может быть установлен
                        Требует: (libgtk-3.so.0()(64bit) or libgtk-4.so.1()(64bit)) но пакет не может быть установлен
E: Unmet dependencies. Try using --fix-broken.
```

Выполнение `# apt-get install --fix-broken` приводит к удалению браузера.

Библиотеки `libcurl` и `libgtk-3` представлены в репозитории и установлены.

**Comment by deemru** [comment]
В случае Linux, тестирую как правило на Ubuntu, [указанной в документации](https://chromium.googlesource.com/chromium/src/+/main/docs/linux/build_instructions.md#System-requirements), установка через `sudo dpkg -i chromium-gost-127.0.6533.88-linux-amd64.deb`, если с установкой и тестами проблем нет -- помечаю релиз для Linux как прошедший испытания.

Вы пишите:
> Обновил браузер с 126.0.6478.182 до 127.0.6533.88

Что это значит? Про `Альте СП 9` ничего не знаю, в нём chromium-gost -- это нативный пакет?

Если да, то вопрос следует направлять тем, кто этот пакет поддерживает.

**Comment by evlanoff** [comment]
> Что это значит?
Версии chromium-gost с какой версии на какую обновился.

> Про Альте СП 9 ничего не знаю,
[Альт СП](https://www.basealt.ru/altsp) версия сертифицированного ФСТЭК дистрибутива Альт Линукс. 

> в нём chromium-gost -- это нативный пакет? Если да, то вопрос следует направлять тем, кто этот пакет поддерживает.

Нет, скачиваю с вашего гитхаба

**Comment by deemru** [comment]
Пока непонятно.

Еще раз: что значит "Обновил браузер"? `dpkg -i` отработал без ошибок?

Браузер обновился после "обновил браузер"? Он работает?

Проблема только с командой `apt-get dist-upgrade` или что-то не работает?

**Comment by evlanoff** [comment]
> Пока непонятно. 
> Еще раз: что значит "Обновил браузер"? dpkg -i отработал без ошибок?

В Альт СП нет команды dpkg. Я установил браузер командой
`rpm -ivh chromium...`, потом обновил уже установленную версию командой `rpm -Uvh chromium...` установка и обновление браузера происходит без проблем.

> Браузер обновился после "обновил браузер"? Он работает?

Да. Всё корректно работает.

> Проблема только с командой apt-get dist-upgrade или что-то не работает?

Проблема в том, что после установки/обновлении chromium-gost до 127 версии при выполнении команды `apt-get dist-upgrade` появляется сообщение которое я опубликовал в самом начале. Браузер работает, но установленный rpm-пакет вызывает unmet dependencies. Если это возможно, предоставьте пожалуйста, SPEC-файлы от 126 и 127 версии браузера для сравнения.

**Comment by evlanoff** [comment]
Изучил приведённые вами ссылки, но увы не понял как из этого получается deb/rpm-пакет, который выкладывается для скачивания.

В публичном репозитории Альт есть [SPEC](https://packages.altlinux.org/en/sisyphus/srpms/chromium-gost/specfiles/)-файл, который создаёт rpm-пакет. Похожий файл есть у вас? Или вы как-то по-другому собираете rpm-пакет?

**Comment by deemru** [comment]
Как уже сказано ранее, никаких дополнительных патчей, связанных с установкой в Chromium-Gost, нет. Собирается релиз на Linux так: https://github.com/deemru/Chromium-Gost/blob/master/build_linux/chromium-gost-build-release.sh

Поэтому, если какие-то изменения произошли, то они произошли в оригинальном репозитории, ссылки на исходники которого приведены выше.

**Comment by evlanoff** [comment]
Изучил подробнее процесс сборки под Linux, наткнулся на [эту](https://source.chromium.org/chromium/chromium/src/+/main:chrome/installer/linux/rpm/additional_deps;drc=00c3708715e5394420942ffc984778345cb50e3f;l=33) строку. Проверил несколько разных версий исходного кода, везде присутствует эта строка, только номер бага меняется.

Что характерно, в их [SPEC](https://source.chromium.org/chromium/chromium/src/+/refs/tags/126.0.6478.182:chrome/installer/linux/rpm/chrome.spec.template;drc=8d9f0d3ffc6f3f391950905f331514e75358f06b;l=22)-файле есть директива, которая явно указывает [отключить](http://ftp.rpm.org/max-rpm/s1-rpm-depend-auto-depend.html#:~:text=simple%20and%20flexible.-,The%20autoreqprov,-%2C%20autoreq%2C%20and) проверку зависимостей.

Могу я вас попросить собрать тестовую версию браузера с "патчами" для тестирования? В файл [additional_deps](https://source.chromium.org/chromium/chromium/src/+/main:chrome/installer/linux/rpm/additional_deps) после 22 строки надо добавить
```
AutoReq: No
AutoProv: No
```

[описание директив](https://habr.com/ru/articles/464993/#:~:text=%D1%80%D0%B5%D0%B4%D0%BA%D0%BE%20%D0%BD%D1%83%D0%B6%D0%BD%D0%BE%20%D1%83%D0%BA%D0%B0%D0%B7%D1%8B%D0%B2%D0%B0%D1%82%D1%8C.-,AutoReq%3A%2C%20AutoProv%3A,-%D0%95%D1%81%D0%BB%D0%B8%20%D0%92%D1%8B%20%D1%81%D0%BE%D0%B1%D0%B8%D1%80%D0%B0%D0%B5%D1%82%D0%B5)

**Comment by deemru** [comment]
Спасибо за наводку, вероятно проблема указана тут:
- [chrome/installer/linux/rpm/additional_deps (126.0.6478.182)](https://source.chromium.org/chromium/chromium/src/+/refs/tags/126.0.6478.182:chrome/installer/linux/rpm/additional_deps)
- [chrome/installer/linux/rpm/additional_deps (127.0.6533.88)](https://source.chromium.org/chromium/chromium/src/+/refs/tags/127.0.6533.88:chrome/installer/linux/rpm/additional_deps)

> RPM 4.13 is required for boolean dependencies

А они с версии 127 версии как раз и начали использовать `or` семантику.

Да, всё верно, посмотрел у них в трекере, они ошибку признали и откатили:
- https://issues.chromium.org/issues/355141776
- https://chromium.googlesource.com/chromium/src/+/00c3708715e5394420942ffc984778345cb50e3f

Видимо сделаем также в следующей версии.

**Comment by evlanoff** [comment]
> Спасибо за наводку, вероятно проблема указана тут:
> RPM 4.13 is required for boolean dependencies

Пожалуйста. Сейчас проверил у меня версия rpm 4.13.0.1, видимо в чём-то другом ошибка. Ну теперь хотя бы понятно, что за ошибка и откуда она появилась.

> А они с версии 127 как раз и начали использовать or семантику.

А что это за семантика?

> Да, всё верно, посмотрел у них в трекере, они ошибку признали и откатили:

Будем следить и тестить.

Спасибо.

**Comment by deemru** [comment]
Проверьте, пожалуйста: https://github.com/deemru/Chromium-Gost/releases/tag/127.0.6533.99
