### ISSUE TITLE
Вход в госуслуги

### ISSUE THREAD

**Issue by hytebackup** [deemru/Chromium-Gost#94]
При переходе на страничку входа в госуслуги, браузер chromium gost её не открывает!  
Ошибка: ERR_Failed 
Страничка: esia.gosuslugi.ru/login/
Версия браузера: 129.0.6668.70
Временно помогает ключ --no-sandbox

**Comment by deemru** [comment]
> Временно помогает ключ --no-sandbox

Какая система и какой CSP?

С первым постом обсуждения ознакомлены?: https://www.cryptopro.ru/forum2/default.aspx?g=posts&t=9991

**Comment by hytebackup** [comment]
> > Временно помогает ключ --no-sandbox
> 
> Какая система и какой CSP?
> 
> С первым постом обсуждения ознакомлены?: https://www.cryptopro.ru/forum2/default.aspx?g=posts&t=9991

Windows 11 23H2
КриптоПРО 5.0.12600 КС1

**Comment by deemru** [comment]
Установил `Windows 11 23H2` + `Chromium-Gost 129.0.6668.70` + `КриптоПро CSP 5.0.13000`, зашёл https://esia.gosuslugi.ru/login/ без проблем, ошибка не воспроизводится.

Разница с вами только в версии CSP, не знаю где брать 5.0.12600, на сайте сейчас крайняя сертифицированная версия 5.0.13000, использовал её.

Попробуйте тоже 5.0.13000, если у вас ошибка сохранится, нужны подробности как воспроизвести на чистой системе.

**Comment by hytebackup** [comment]
Обновил до 5.0.13000 всё заработало! Значит проблема была в CSP
