### ISSUE TITLE
Постоянные проблемы с www.gosuslugi.ru

### ISSUE THREAD

**Issue by barulev** [deemru/Chromium-Gost#95]
Перестало работать портал в части авторизации по ЭЦП через хромиум гост (обновление на 130.0.6723.92 не решило проблему).
При попытке войти пишет ошибку:

![image](https://github.com/user-attachments/assets/0b643c32-0b39-4973-adf3-358c5bc77da6)

раньше помогала команда
netsh winsock reset и перезагрузка компа, но сейчас нет

Если попробовать снести крипто 5 (CryptoPro-5.0.12800) и заново поставить, то проблема уходит на какое-то время.

ОС win10 22H2 19045.5011

**Comment by deemru** [comment]
Страница с ошибкой выглядит странно, как будто сам сервер её выдаёт.

Страница с ошибкой в браузере обычно выглядит иначе.

Версия CSP у вас несертифицированная, лучше тоже обновиться, возможно поможет: https://github.com/deemru/Chromium-Gost/issues/94

Если ошибка стабильно воспроизводится, опишите по шагам, как воспроизвести на чистой системе.

**Comment by barulev** [comment]
Благодарю, всё получилось и заработало
ура! )
