### ISSUE TITLE
Не открывает сайт https://ecp.sfr.gov.ru/new-reg-num

### ISSUE THREAD

**Issue by 19TNR82** [deemru/Chromium-Gost#96]
Этот сайт не может обеспечить безопасное подключение
Сайт ecp.sfr.gov.ru отправил недействительный ответ.

ERR_SSL_PROTOCOL_ERROR

Сертификат действующий, цепочка до УЦ строится. В Яндекс браузере открывает нормально.
![chrome_M1J9URlufY](https://github.com/user-attachments/assets/88c260bb-2c35-498e-82c6-ecc7cc3db81c)

**Comment by deemru** [comment]
Сайт очень специфически (некорректно) работает с TLS 1.3 при появлении упоминаний ГОСТ.

Поэтому можно отключить ГОСТ TLS 1.3:
```cmd
reg add "HKLM\SOFTWARE\WOW6432Node\Crypto Pro\Cryptography\CurrentVersion\Parameters\Protocols\TLS 1.3\Client" /v Enabled /t REG_DWORD /d 0 /f
```

Можно работать [без ГОСТ](https://github.com/deemru/Chromium-Gost/wiki/tlsmode):
```cmd
chrome --tlsmode=-1
```
