### ISSUE TITLE
Служба ChromiumElevationService

### ISSUE THREAD

**Issue by saym101** [deemru/Chromium-Gost#97]
После установки на сервер для всех пользователей появляется служба - ChromiumElevationService. Которая указывает на отсутствующий файл "C:\Program Files\Chromium\Application\130.0.6723.92\elevation_service.exe" Из-за этого в лог сыпяться ошибки о не возможности ее запуска. И сколько людей её запускают, столько и ошибок, от каждого пользователя по ошибке. Помогает отключение службы. 
Поправьте.

**Comment by deemru** [comment]
Необходимость данной службы в сборке Chromium-Gost непонятна, ранее просто никто не замечал видимо.

> Помогает отключение службы.

Получается, что это нормальное решение.

Добавили в патч пропуск установки службы в инсталлере: https://github.com/deemru/Chromium-Gost/commit/e60ce2a2a889f72a20dcd9d89c458b6836ee67f6

В следующей версии установки службы не будет, но, чтобы служба удалилась штатно, необходимо будет произвести разовое удаление приложения: https://github.com/deemru/Chromium-Gost/issues/30#issuecomment-804008864

**Comment by saym101** [comment]
Удалить уже не получится, много народу на ней сидит уже. Боюсь информация пропадет. наличие пункта в службах на работу сервера не влияет. При желании можно ручками удалить через реестр.
Спасибо.

**Comment by deemru** [comment]
Исправлено начиная с https://github.com/deemru/Chromium-Gost/releases/tag/131.0.6778.108
